@echo off
echo Creating Other Natural Science folder structure with subfolders...

mkdir "Other_Natural_Science"
cd "Other_Natural_Science"

mkdir Anthropology "English Skill II" "Emerging Technologies" History "Moral and Citizenship Education" Chemistry Biology Economics

REM ========== ANTHROPOLOGY ==========
mkdir "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\video" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\quiz" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\exam" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\past_paper" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\short_note" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\flashcard"
mkdir "Anthropology\Unit 2_ Human Culture and Ties that Connect\video" "Anthropology\Unit 2_ Human Culture and Ties that Connect\quiz" "Anthropology\Unit 2_ Human Culture and Ties that Connect\exam" "Anthropology\Unit 2_ Human Culture and Ties that Connect\past_paper" "Anthropology\Unit 2_ Human Culture and Ties that Connect\short_note" "Anthropology\Unit 2_ Human Culture and Ties that Connect\flashcard"
mkdir "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\video" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\quiz" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\exam" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\past_paper" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\short_note" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\flashcard"
mkdir "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\video" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\quiz" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\exam" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\past_paper" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\short_note" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\flashcard"
mkdir "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\video" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\quiz" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\exam" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\past_paper" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\short_note" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\flashcard"
mkdir "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\video" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\quiz" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\exam" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\past_paper" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\short_note" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\flashcard"
mkdir "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\video" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\quiz" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\exam" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\past_paper" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\short_note" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\flashcard"

REM ========== ENGLISH SKILL II ==========
mkdir "English Skill II\Unit 1_ Life Skills\video" "English Skill II\Unit 1_ Life Skills\quiz" "English Skill II\Unit 1_ Life Skills\exam" "English Skill II\Unit 1_ Life Skills\past_paper" "English Skill II\Unit 1_ Life Skills\short_note" "English Skill II\Unit 1_ Life Skills\flashcard"
mkdir "English Skill II\Unit 2_ Speculations about the future of Science\video" "English Skill II\Unit 2_ Speculations about the future of Science\quiz" "English Skill II\Unit 2_ Speculations about the future of Science\exam" "English Skill II\Unit 2_ Speculations about the future of Science\past_paper" "English Skill II\Unit 2_ Speculations about the future of Science\short_note" "English Skill II\Unit 2_ Speculations about the future of Science\flashcard"
mkdir "English Skill II\Unit 3_ Environmental Protection\video" "English Skill II\Unit 3_ Environmental Protection\quiz" "English Skill II\Unit 3_ Environmental Protection\exam" "English Skill II\Unit 3_ Environmental Protection\past_paper" "English Skill II\Unit 3_ Environmental Protection\short_note" "English Skill II\Unit 3_ Environmental Protection\flashcard"
mkdir "English Skill II\Unit 4_ Indigenous Knowledge\video" "English Skill II\Unit 4_ Indigenous Knowledge\quiz" "English Skill II\Unit 4_ Indigenous Knowledge\exam" "English Skill II\Unit 4_ Indigenous Knowledge\past_paper" "English Skill II\Unit 4_ Indigenous Knowledge\short_note" "English Skill II\Unit 4_ Indigenous Knowledge\flashcard"
mkdir "English Skill II\Unit 5_ Cultural Heritage\video" "English Skill II\Unit 5_ Cultural Heritage\quiz" "English Skill II\Unit 5_ Cultural Heritage\exam" "English Skill II\Unit 5_ Cultural Heritage\past_paper" "English Skill II\Unit 5_ Cultural Heritage\short_note" "English Skill II\Unit 5_ Cultural Heritage\flashcard"

REM ========== EMERGING TECHNOLOGIES ==========
mkdir "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\video" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\quiz" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\exam" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\past_paper" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\short_note" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\flashcard"
mkdir "Emerging Technologies\Chapter 2_ Overview for Data Science\video" "Emerging Technologies\Chapter 2_ Overview for Data Science\quiz" "Emerging Technologies\Chapter 2_ Overview for Data Science\exam" "Emerging Technologies\Chapter 2_ Overview for Data Science\past_paper" "Emerging Technologies\Chapter 2_ Overview for Data Science\short_note" "Emerging Technologies\Chapter 2_ Overview for Data Science\flashcard"
mkdir "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\video" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\quiz" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\exam" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\past_paper" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\short_note" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\flashcard"
mkdir "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\video" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\quiz" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\exam" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\past_paper" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\short_note" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\flashcard"
mkdir "Emerging Technologies\Chapter 5_ Augmented Reality\video" "Emerging Technologies\Chapter 5_ Augmented Reality\quiz" "Emerging Technologies\Chapter 5_ Augmented Reality\exam" "Emerging Technologies\Chapter 5_ Augmented Reality\past_paper" "Emerging Technologies\Chapter 5_ Augmented Reality\short_note" "Emerging Technologies\Chapter 5_ Augmented Reality\flashcard"
mkdir "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\video" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\quiz" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\exam" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\past_paper" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\short_note" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\flashcard"
mkdir "Emerging Technologies\Chapter 7_ Other Emerging Technologies\video" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\quiz" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\exam" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\past_paper" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\short_note" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\flashcard"

REM ========== HISTORY ==========
mkdir "History\Chapter 1_ introduction\video" "History\Chapter 1_ introduction\quiz" "History\Chapter 1_ introduction\exam" "History\Chapter 1_ introduction\past_paper" "History\Chapter 1_ introduction\short_note" "History\Chapter 1_ introduction\flashcard"
mkdir "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\video" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\quiz" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\exam" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\past_paper" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\short_note" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\flashcard"
mkdir "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\video" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\quiz" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\exam" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\past_paper" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\short_note" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\flashcard"
mkdir "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\video" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\quiz" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\exam" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\past_paper" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\short_note" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\flashcard"
mkdir "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\video" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\quiz" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\exam" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\past_paper" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\short_note" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\flashcard"
mkdir "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\video" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\quiz" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\exam" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\past_paper" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\short_note" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\flashcard"
mkdir "History\Chapter 7_ internal developments and external relations, 1941-1994\video" "History\Chapter 7_ internal developments and external relations, 1941-1994\quiz" "History\Chapter 7_ internal developments and external relations, 1941-1994\exam" "History\Chapter 7_ internal developments and external relations, 1941-1994\past_paper" "History\Chapter 7_ internal developments and external relations, 1941-1994\short_note" "History\Chapter 7_ internal developments and external relations, 1941-1994\flashcard"

REM ========== MORAL AND CITIZENSHIP EDUCATION ==========
mkdir "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\video" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\quiz" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\exam" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\past_paper" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\short_note" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\flashcard"
mkdir "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\video" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\quiz" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\exam" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\past_paper" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\short_note" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\flashcard"
mkdir "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\video" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\quiz" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\exam" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\past_paper" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\short_note" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\flashcard"
mkdir "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\video" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\quiz" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\exam" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\past_paper" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\short_note" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\flashcard"
mkdir "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\video" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\quiz" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\exam" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\past_paper" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\short_note" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\flashcard"

REM ========== CHEMISTRY ==========
mkdir "Chemistry\Chapter 1_ essential ideas in chemistry\video" "Chemistry\Chapter 1_ essential ideas in chemistry\quiz" "Chemistry\Chapter 1_ essential ideas in chemistry\exam" "Chemistry\Chapter 1_ essential ideas in chemistry\past_paper" "Chemistry\Chapter 1_ essential ideas in chemistry\short_note" "Chemistry\Chapter 1_ essential ideas in chemistry\flashcard"
mkdir "Chemistry\Chapter 2_ atoms, molecules and ions\video" "Chemistry\Chapter 2_ atoms, molecules and ions\quiz" "Chemistry\Chapter 2_ atoms, molecules and ions\exam" "Chemistry\Chapter 2_ atoms, molecules and ions\past_paper" "Chemistry\Chapter 2_ atoms, molecules and ions\short_note" "Chemistry\Chapter 2_ atoms, molecules and ions\flashcard"
mkdir "Chemistry\Chapter 3_ mass and mole concept\video" "Chemistry\Chapter 3_ mass and mole concept\quiz" "Chemistry\Chapter 3_ mass and mole concept\exam" "Chemistry\Chapter 3_ mass and mole concept\past_paper" "Chemistry\Chapter 3_ mass and mole concept\short_note" "Chemistry\Chapter 3_ mass and mole concept\flashcard"
mkdir "Chemistry\Chapter 4_ stoichiometry of chemical reaction\video" "Chemistry\Chapter 4_ stoichiometry of chemical reaction\quiz" "Chemistry\Chapter 4_ stoichiometry of chemical reaction\exam" "Chemistry\Chapter 4_ stoichiometry of chemical reaction\past_paper" "Chemistry\Chapter 4_ stoichiometry of chemical reaction\short_note" "Chemistry\Chapter 4_ stoichiometry of chemical reaction\flashcard"
mkdir "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\video" "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\quiz" "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\exam" "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\past_paper" "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\short_note" "Chemistry\Chapter 5_ electronic structure and periodic properties of elements\flashcard"
mkdir "Chemistry\Chapter 6_ chemical bonding and molecular geometry\video" "Chemistry\Chapter 6_ chemical bonding and molecular geometry\quiz" "Chemistry\Chapter 6_ chemical bonding and molecular geometry\exam" "Chemistry\Chapter 6_ chemical bonding and molecular geometry\past_paper" "Chemistry\Chapter 6_ chemical bonding and molecular geometry\short_note" "Chemistry\Chapter 6_ chemical bonding and molecular geometry\flashcard"
mkdir "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\video" "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\quiz" "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\exam" "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\past_paper" "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\short_note" "Chemistry\Chapter 7_ equilibrium concepts and acid base equilibrium\flashcard"
mkdir "Chemistry\Chapter 8_ organic chemistry\video" "Chemistry\Chapter 8_ organic chemistry\quiz" "Chemistry\Chapter 8_ organic chemistry\exam" "Chemistry\Chapter 8_ organic chemistry\past_paper" "Chemistry\Chapter 8_ organic chemistry\short_note" "Chemistry\Chapter 8_ organic chemistry\flashcard"

REM ========== BIOLOGY ==========
mkdir "Biology\Chapter 1_ introduction\video" "Biology\Chapter 1_ introduction\quiz" "Biology\Chapter 1_ introduction\exam" "Biology\Chapter 1_ introduction\past_paper" "Biology\Chapter 1_ introduction\short_note" "Biology\Chapter 1_ introduction\flashcard"
mkdir "Biology\Chapter 2_ biological molecules\video" "Biology\Chapter 2_ biological molecules\quiz" "Biology\Chapter 2_ biological molecules\exam" "Biology\Chapter 2_ biological molecules\past_paper" "Biology\Chapter 2_ biological molecules\short_note" "Biology\Chapter 2_ biological molecules\flashcard"
mkdir "Biology\Chapter 3_ the cellular basics of life\video" "Biology\Chapter 3_ the cellular basics of life\quiz" "Biology\Chapter 3_ the cellular basics of life\exam" "Biology\Chapter 3_ the cellular basics of life\past_paper" "Biology\Chapter 3_ the cellular basics of life\short_note" "Biology\Chapter 3_ the cellular basics of life\flashcard"
mkdir "Biology\Chapter 4_ cellular metabolism and metabolic disorder\video" "Biology\Chapter 4_ cellular metabolism and metabolic disorder\quiz" "Biology\Chapter 4_ cellular metabolism and metabolic disorder\exam" "Biology\Chapter 4_ cellular metabolism and metabolic disorder\past_paper" "Biology\Chapter 4_ cellular metabolism and metabolic disorder\short_note" "Biology\Chapter 4_ cellular metabolism and metabolic disorder\flashcard"
mkdir "Biology\Chapter 5_ genetics and evolution\video" "Biology\Chapter 5_ genetics and evolution\quiz" "Biology\Chapter 5_ genetics and evolution\exam" "Biology\Chapter 5_ genetics and evolution\past_paper" "Biology\Chapter 5_ genetics and evolution\short_note" "Biology\Chapter 5_ genetics and evolution\flashcard"
mkdir "Biology\Chapter 6_ infectious diseases and immunity\video" "Biology\Chapter 6_ infectious diseases and immunity\quiz" "Biology\Chapter 6_ infectious diseases and immunity\exam" "Biology\Chapter 6_ infectious diseases and immunity\past_paper" "Biology\Chapter 6_ infectious diseases and immunity\short_note" "Biology\Chapter 6_ infectious diseases and immunity\flashcard"
mkdir "Biology\Chapter 7_ taxonomy of organism\video" "Biology\Chapter 7_ taxonomy of organism\quiz" "Biology\Chapter 7_ taxonomy of organism\exam" "Biology\Chapter 7_ taxonomy of organism\past_paper" "Biology\Chapter 7_ taxonomy of organism\short_note" "Biology\Chapter 7_ taxonomy of organism\flashcard"
mkdir "Biology\Chapter 8_ ecology and conservation of natural resources\video" "Biology\Chapter 8_ ecology and conservation of natural resources\quiz" "Biology\Chapter 8_ ecology and conservation of natural resources\exam" "Biology\Chapter 8_ ecology and conservation of natural resources\past_paper" "Biology\Chapter 8_ ecology and conservation of natural resources\short_note" "Biology\Chapter 8_ ecology and conservation of natural resources\flashcard"
mkdir "Biology\Chapter 9_ introduction to botany and zoology\video" "Biology\Chapter 9_ introduction to botany and zoology\quiz" "Biology\Chapter 9_ introduction to botany and zoology\exam" "Biology\Chapter 9_ introduction to botany and zoology\past_paper" "Biology\Chapter 9_ introduction to botany and zoology\short_note" "Biology\Chapter 9_ introduction to botany and zoology\flashcard"
mkdir "Biology\Chapter 10_ application of biological science\video" "Biology\Chapter 10_ application of biological science\quiz" "Biology\Chapter 10_ application of biological science\exam" "Biology\Chapter 10_ application of biological science\past_paper" "Biology\Chapter 10_ application of biological science\short_note" "Biology\Chapter 10_ application of biological science\flashcard"

REM ========== ECONOMICS ==========
mkdir "Economics\Chapter 1_ basics of economics\video" "Economics\Chapter 1_ basics of economics\quiz" "Economics\Chapter 1_ basics of economics\exam" "Economics\Chapter 1_ basics of economics\past_paper" "Economics\Chapter 1_ basics of economics\short_note" "Economics\Chapter 1_ basics of economics\flashcard"
mkdir "Economics\Chapter 2_ theory of demand and supply\video" "Economics\Chapter 2_ theory of demand and supply\quiz" "Economics\Chapter 2_ theory of demand and supply\exam" "Economics\Chapter 2_ theory of demand and supply\past_paper" "Economics\Chapter 2_ theory of demand and supply\short_note" "Economics\Chapter 2_ theory of demand and supply\flashcard"
mkdir "Economics\Chapter 3_ theory of customer behaviour\video" "Economics\Chapter 3_ theory of customer behaviour\quiz" "Economics\Chapter 3_ theory of customer behaviour\exam" "Economics\Chapter 3_ theory of customer behaviour\past_paper" "Economics\Chapter 3_ theory of customer behaviour\short_note" "Economics\Chapter 3_ theory of customer behaviour\flashcard"
mkdir "Economics\Chapter 4_ the theory of production and cost\video" "Economics\Chapter 4_ the theory of production and cost\quiz" "Economics\Chapter 4_ the theory of production and cost\exam" "Economics\Chapter 4_ the theory of production and cost\past_paper" "Economics\Chapter 4_ the theory of production and cost\short_note" "Economics\Chapter 4_ the theory of production and cost\flashcard"
mkdir "Economics\Chapter 5_ market structure\video" "Economics\Chapter 5_ market structure\quiz" "Economics\Chapter 5_ market structure\exam" "Economics\Chapter 5_ market structure\past_paper" "Economics\Chapter 5_ market structure\short_note" "Economics\Chapter 5_ market structure\flashcard"
mkdir "Economics\Chapter 6_ fundamental concepts of macroeconomics\video" "Economics\Chapter 6_ fundamental concepts of macroeconomics\quiz" "Economics\Chapter 6_ fundamental concepts of macroeconomics\exam" "Economics\Chapter 6_ fundamental concepts of macroeconomics\past_paper" "Economics\Chapter 6_ fundamental concepts of macroeconomics\short_note" "Economics\Chapter 6_ fundamental concepts of macroeconomics\flashcard"

echo Other Natural Science folder structure completed!
pause