@echo off
echo Creating Grade 9 folder structure with subfolders...

mkdir "Grade_9"
cd "Grade_9"

mkdir mathematics physics chemistry biology economics history geography citizenship it english

REM ========== MATHEMATICS ==========
mkdir "mathematics\Unit 1_ FURTHER ON SETS\video" "mathematics\Unit 1_ FURTHER ON SETS\quiz" "mathematics\Unit 1_ FURTHER ON SETS\exam" "mathematics\Unit 1_ FURTHER ON SETS\past_paper" "mathematics\Unit 1_ FURTHER ON SETS\short_note" "mathematics\Unit 1_ FURTHER ON SETS\flashcard"
mkdir "mathematics\Unit 2_ THE NUMBER SYSTEM\video" "mathematics\Unit 2_ THE NUMBER SYSTEM\quiz" "mathematics\Unit 2_ THE NUMBER SYSTEM\exam" "mathematics\Unit 2_ THE NUMBER SYSTEM\past_paper" "mathematics\Unit 2_ THE NUMBER SYSTEM\short_note" "mathematics\Unit 2_ THE NUMBER SYSTEM\flashcard"
mkdir "mathematics\Unit 3_ SOLVING EQUATIONS\video" "mathematics\Unit 3_ SOLVING EQUATIONS\quiz" "mathematics\Unit 3_ SOLVING EQUATIONS\exam" "mathematics\Unit 3_ SOLVING EQUATIONS\past_paper" "mathematics\Unit 3_ SOLVING EQUATIONS\short_note" "mathematics\Unit 3_ SOLVING EQUATIONS\flashcard"
mkdir "mathematics\Unit 4_ SOLVING INEQUALITIES\video" "mathematics\Unit 4_ SOLVING INEQUALITIES\quiz" "mathematics\Unit 4_ SOLVING INEQUALITIES\exam" "mathematics\Unit 4_ SOLVING INEQUALITIES\past_paper" "mathematics\Unit 4_ SOLVING INEQUALITIES\short_note" "mathematics\Unit 4_ SOLVING INEQUALITIES\flashcard"
mkdir "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\video" "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\quiz" "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\exam" "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\past_paper" "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\short_note" "mathematics\Unit 5_ INTRODUCTION TO TRIGONOMETRY\flashcard"
mkdir "mathematics\Unit 6_ REGULAR POLYGONS\video" "mathematics\Unit 6_ REGULAR POLYGONS\quiz" "mathematics\Unit 6_ REGULAR POLYGONS\exam" "mathematics\Unit 6_ REGULAR POLYGONS\past_paper" "mathematics\Unit 6_ REGULAR POLYGONS\short_note" "mathematics\Unit 6_ REGULAR POLYGONS\flashcard"
mkdir "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\video" "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\quiz" "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\exam" "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\past_paper" "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\short_note" "mathematics\Unit 7_ CONGRUENCY AND SIMILARITY\flashcard"
mkdir "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\video" "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\quiz" "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\exam" "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\past_paper" "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\short_note" "mathematics\Unit 8_ VECTORS IN TWO DIMENSIONS\flashcard"
mkdir "mathematics\Unit 9_ STATISTICS AND PROBABILITY\video" "mathematics\Unit 9_ STATISTICS AND PROBABILITY\quiz" "mathematics\Unit 9_ STATISTICS AND PROBABILITY\exam" "mathematics\Unit 9_ STATISTICS AND PROBABILITY\past_paper" "mathematics\Unit 9_ STATISTICS AND PROBABILITY\short_note" "mathematics\Unit 9_ STATISTICS AND PROBABILITY\flashcard"

REM ========== PHYSICS ==========
mkdir "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\video" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\quiz" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\exam" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\past_paper" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\short_note" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\flashcard"
mkdir "physics\Unit 2_ PHYSICAL QUANTITIES\video" "physics\Unit 2_ PHYSICAL QUANTITIES\quiz" "physics\Unit 2_ PHYSICAL QUANTITIES\exam" "physics\Unit 2_ PHYSICAL QUANTITIES\past_paper" "physics\Unit 2_ PHYSICAL QUANTITIES\short_note" "physics\Unit 2_ PHYSICAL QUANTITIES\flashcard"
mkdir "physics\Unit 3_ MOTION IN A STRAIGHT LINE\video" "physics\Unit 3_ MOTION IN A STRAIGHT LINE\quiz" "physics\Unit 3_ MOTION IN A STRAIGHT LINE\exam" "physics\Unit 3_ MOTION IN A STRAIGHT LINE\past_paper" "physics\Unit 3_ MOTION IN A STRAIGHT LINE\short_note" "physics\Unit 3_ MOTION IN A STRAIGHT LINE\flashcard"
mkdir "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\video" "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\quiz" "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\exam" "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\past_paper" "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\short_note" "physics\Unit 4_ FORCE, WORK, ENERGY AND POWER\flashcard"
mkdir "physics\Unit 5_ SIMPLE MACHINES\video" "physics\Unit 5_ SIMPLE MACHINES\quiz" "physics\Unit 5_ SIMPLE MACHINES\exam" "physics\Unit 5_ SIMPLE MACHINES\past_paper" "physics\Unit 5_ SIMPLE MACHINES\short_note" "physics\Unit 5_ SIMPLE MACHINES\flashcard"
mkdir "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\video" "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\quiz" "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\exam" "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\past_paper" "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\short_note" "physics\Unit 6_ MECHANICAL OSCILLATION AND SOUND WAVE\flashcard"
mkdir "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\video" "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\quiz" "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\exam" "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\past_paper" "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\short_note" "physics\Unit 7_ TEMPERATURE AND THERMOMETRY\flashcard"

REM ========== CHEMISTRY ==========
mkdir "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\video" "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\quiz" "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\exam" "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\past_paper" "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\short_note" "chemistry\Unit 1_ CHEMISTRY AND ITS IMPORTANCE\flashcard"
mkdir "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\video" "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\quiz" "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\exam" "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\past_paper" "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\short_note" "chemistry\Unit 2_ MEASUREMENTS AND SCIENTIFIC METHODS\flashcard"
mkdir "chemistry\Unit 3_ STRUCTURE OF THE ATOM\video" "chemistry\Unit 3_ STRUCTURE OF THE ATOM\quiz" "chemistry\Unit 3_ STRUCTURE OF THE ATOM\exam" "chemistry\Unit 3_ STRUCTURE OF THE ATOM\past_paper" "chemistry\Unit 3_ STRUCTURE OF THE ATOM\short_note" "chemistry\Unit 3_ STRUCTURE OF THE ATOM\flashcard"
mkdir "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\video" "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\quiz" "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\exam" "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\past_paper" "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\short_note" "chemistry\Unit 4_ PERIODIC CLASSIFICATION OF ELEMENTS\flashcard"
mkdir "chemistry\Unit 5_ CHEMICAL BONDING\video" "chemistry\Unit 5_ CHEMICAL BONDING\quiz" "chemistry\Unit 5_ CHEMICAL BONDING\exam" "chemistry\Unit 5_ CHEMICAL BONDING\past_paper" "chemistry\Unit 5_ CHEMICAL BONDING\short_note" "chemistry\Unit 5_ CHEMICAL BONDING\flashcard"

REM ========== BIOLOGY ==========
mkdir "biology\Unit 1_ INTRODUCTION TO BIOLOGY\video" "biology\Unit 1_ INTRODUCTION TO BIOLOGY\quiz" "biology\Unit 1_ INTRODUCTION TO BIOLOGY\exam" "biology\Unit 1_ INTRODUCTION TO BIOLOGY\past_paper" "biology\Unit 1_ INTRODUCTION TO BIOLOGY\short_note" "biology\Unit 1_ INTRODUCTION TO BIOLOGY\flashcard"
mkdir "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\video" "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\quiz" "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\exam" "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\past_paper" "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\short_note" "biology\Unit 2_ CHARACTERISTICS AND CLASSIFICATION OF ORGANISMS\flashcard"
mkdir "biology\Unit 3_ CELLS\video" "biology\Unit 3_ CELLS\quiz" "biology\Unit 3_ CELLS\exam" "biology\Unit 3_ CELLS\past_paper" "biology\Unit 3_ CELLS\short_note" "biology\Unit 3_ CELLS\flashcard"
mkdir "biology\Unit 4_ REPRODUCTION\video" "biology\Unit 4_ REPRODUCTION\quiz" "biology\Unit 4_ REPRODUCTION\exam" "biology\Unit 4_ REPRODUCTION\past_paper" "biology\Unit 4_ REPRODUCTION\short_note" "biology\Unit 4_ REPRODUCTION\flashcard"
mkdir "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\video" "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\quiz" "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\exam" "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\past_paper" "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\short_note" "biology\Unit 5_ HUMAN HEALTH, NUTRITION, AND DISEASE\flashcard"
mkdir "biology\Unit 6_ ECOLOGY\video" "biology\Unit 6_ ECOLOGY\quiz" "biology\Unit 6_ ECOLOGY\exam" "biology\Unit 6_ ECOLOGY\past_paper" "biology\Unit 6_ ECOLOGY\short_note" "biology\Unit 6_ ECOLOGY\flashcard"

REM ========== ECONOMICS ==========
mkdir "economics\Unit 1_ INTRODUCING ECONOMICS\video" "economics\Unit 1_ INTRODUCING ECONOMICS\quiz" "economics\Unit 1_ INTRODUCING ECONOMICS\exam" "economics\Unit 1_ INTRODUCING ECONOMICS\past_paper" "economics\Unit 1_ INTRODUCING ECONOMICS\short_note" "economics\Unit 1_ INTRODUCING ECONOMICS\flashcard"
mkdir "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\video" "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\quiz" "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\exam" "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\past_paper" "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\short_note" "economics\Unit 2_ THE BASIC ECONOMIC PROBLEMS AND ECONOMIC SYSTEMS\flashcard"
mkdir "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\video" "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\quiz" "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\exam" "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\past_paper" "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\short_note" "economics\Unit 3_ ECONOMIC RESOURCES AND MARKETS\flashcard"
mkdir "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\video" "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\quiz" "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\exam" "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\past_paper" "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\short_note" "economics\Unit 4_ INTRODUCTION TO DEMAND AND SUPPLY\flashcard"
mkdir "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\video" "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\quiz" "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\exam" "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\past_paper" "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\short_note" "economics\Unit 5_ INTRODUCTION TO PRODUCTION AND COST\flashcard"
mkdir "economics\Unit 6_ INTRODUCTION TO MONEY\video" "economics\Unit 6_ INTRODUCTION TO MONEY\quiz" "economics\Unit 6_ INTRODUCTION TO MONEY\exam" "economics\Unit 6_ INTRODUCTION TO MONEY\past_paper" "economics\Unit 6_ INTRODUCTION TO MONEY\short_note" "economics\Unit 6_ INTRODUCTION TO MONEY\flashcard"
mkdir "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\video" "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\quiz" "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\exam" "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\past_paper" "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\short_note" "economics\Unit 7_ INTRODUCTION TO MACROECONOMICS\flashcard"
mkdir "economics\Unit 8_ BASIC ENTREPRENEURSHIP\video" "economics\Unit 8_ BASIC ENTREPRENEURSHIP\quiz" "economics\Unit 8_ BASIC ENTREPRENEURSHIP\exam" "economics\Unit 8_ BASIC ENTREPRENEURSHIP\past_paper" "economics\Unit 8_ BASIC ENTREPRENEURSHIP\short_note" "economics\Unit 8_ BASIC ENTREPRENEURSHIP\flashcard"

REM ========== HISTORY ==========
mkdir "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\video" "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\quiz" "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\exam" "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\past_paper" "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\short_note" "history\Unit 1_ THE DISCIPLINE OF HISTORY AND HUMAN EVOLUTION\flashcard"
mkdir "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\video" "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\quiz" "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\exam" "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\past_paper" "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\short_note" "history\Unit 2_ ANCIENT WORLD CIVILIZATIONS UP TO c. 500 AD\flashcard"
mkdir "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\video" "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\quiz" "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\exam" "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\past_paper" "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\short_note" "history\Unit 3_ PEOPLES AND STATES IN ETHIOPIA AND THE HORN TO THE END OF 13th C.\flashcard"
mkdir "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\video" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\quiz" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\exam" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\past_paper" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\short_note" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 TO 1750s\flashcard"
mkdir "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\video" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\quiz" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\exam" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\past_paper" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\short_note" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\flashcard"
mkdir "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\video" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\quiz" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\exam" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\past_paper" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\short_note" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\flashcard"
mkdir "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\video" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\quiz" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\exam" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\past_paper" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\short_note" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS & INTERACTIONS IN ETHIOPIA 13th TO MID-16th C.\flashcard"
mkdir "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\video" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\quiz" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\exam" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\past_paper" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\short_note" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA MID-16th TO MID-19th C.\flashcard"
mkdir "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\video" "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\quiz" "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\exam" "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\past_paper" "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\short_note" "history\Unit 9_ THE AGE OF REVOLUTIONS 1750s TO 1815\flashcard"

REM ========== GEOGRAPHY ==========
mkdir "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\video" "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\quiz" "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\exam" "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\past_paper" "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\short_note" "geography\Unit 1_ INTRODUCTION TO GEOGRAPHY\flashcard"
mkdir "geography\Unit 2_ THE EARTH\video" "geography\Unit 2_ THE EARTH\quiz" "geography\Unit 2_ THE EARTH\exam" "geography\Unit 2_ THE EARTH\past_paper" "geography\Unit 2_ THE EARTH\short_note" "geography\Unit 2_ THE EARTH\flashcard"
mkdir "geography\Unit 3_ MAP READING AND INTERPRETATION\video" "geography\Unit 3_ MAP READING AND INTERPRETATION\quiz" "geography\Unit 3_ MAP READING AND INTERPRETATION\exam" "geography\Unit 3_ MAP READING AND INTERPRETATION\past_paper" "geography\Unit 3_ MAP READING AND INTERPRETATION\short_note" "geography\Unit 3_ MAP READING AND INTERPRETATION\flashcard"
mkdir "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\video" "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\quiz" "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\exam" "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\past_paper" "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\short_note" "geography\Unit 4_ THE PHYSICAL ENVIRONMENT OF ETHIOPIA\flashcard"
mkdir "geography\Unit 5_ POPULATION OF ETHIOPIA\video" "geography\Unit 5_ POPULATION OF ETHIOPIA\quiz" "geography\Unit 5_ POPULATION OF ETHIOPIA\exam" "geography\Unit 5_ POPULATION OF ETHIOPIA\past_paper" "geography\Unit 5_ POPULATION OF ETHIOPIA\short_note" "geography\Unit 5_ POPULATION OF ETHIOPIA\flashcard"
mkdir "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\video" "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\quiz" "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\exam" "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\past_paper" "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\short_note" "geography\Unit 6_ ECONOMIC ACTIVITIES IN ETHIOPIA\flashcard"

REM ========== CITIZENSHIP ==========
mkdir "citizenship\Unit 1_ ETHICAL VALUES\video" "citizenship\Unit 1_ ETHICAL VALUES\quiz" "citizenship\Unit 1_ ETHICAL VALUES\exam" "citizenship\Unit 1_ ETHICAL VALUES\past_paper" "citizenship\Unit 1_ ETHICAL VALUES\short_note" "citizenship\Unit 1_ ETHICAL VALUES\flashcard"
mkdir "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\video" "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\quiz" "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\exam" "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\past_paper" "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\short_note" "citizenship\Unit 2_ THE CULTURE OF USING DIGITAL TECHNOLOGY\flashcard"
mkdir "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\video" "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\quiz" "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\exam" "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\past_paper" "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\short_note" "citizenship\Unit 3_ CONSTITUTION AND CONSTITUTIONALISM\flashcard"
mkdir "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\video" "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\quiz" "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\exam" "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\past_paper" "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\short_note" "citizenship\Unit 4_ UNDERSTANDING INDIGENOUS KNOWLEDGE\flashcard"
mkdir "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\video" "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\quiz" "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\exam" "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\past_paper" "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\short_note" "citizenship\Unit 5_ MULTICULTURALISM IN ETHIOPIA\flashcard"
mkdir "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\video" "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\quiz" "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\exam" "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\past_paper" "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\short_note" "citizenship\Unit 6_ NATIONAL UNITY THROUGH DIVERSITY\flashcard"
mkdir "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\video" "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\quiz" "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\exam" "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\past_paper" "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\short_note" "citizenship\Unit 7_ PROBLEM SOLVING SKILLS\flashcard"
mkdir "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\video" "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\quiz" "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\exam" "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\past_paper" "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\short_note" "citizenship\Unit 8_ ETHIOPIA'S FOREIGN RELATIONS IN EAST AFRICA\flashcard"

REM ========== IT ==========
mkdir "it\Unit 1_ ORGANIZATION OF FILES\video" "it\Unit 1_ ORGANIZATION OF FILES\quiz" "it\Unit 1_ ORGANIZATION OF FILES\exam" "it\Unit 1_ ORGANIZATION OF FILES\past_paper" "it\Unit 1_ ORGANIZATION OF FILES\short_note" "it\Unit 1_ ORGANIZATION OF FILES\flashcard"
mkdir "it\Unit 2_ COMPUTER NETWORK\video" "it\Unit 2_ COMPUTER NETWORK\quiz" "it\Unit 2_ COMPUTER NETWORK\exam" "it\Unit 2_ COMPUTER NETWORK\past_paper" "it\Unit 2_ COMPUTER NETWORK\short_note" "it\Unit 2_ COMPUTER NETWORK\flashcard"
mkdir "it\Unit 3_ APPLICATION SOFTWARE\video" "it\Unit 3_ APPLICATION SOFTWARE\quiz" "it\Unit 3_ APPLICATION SOFTWARE\exam" "it\Unit 3_ APPLICATION SOFTWARE\past_paper" "it\Unit 3_ APPLICATION SOFTWARE\short_note" "it\Unit 3_ APPLICATION SOFTWARE\flashcard"
mkdir "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\video" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\quiz" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\exam" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\past_paper" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\short_note" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\flashcard"
mkdir "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\video" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\quiz" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\exam" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\past_paper" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\short_note" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\flashcard"
mkdir "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\video" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\quiz" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\exam" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\past_paper" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\short_note" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Unit 1_ LIVING IN URBAN AREAS\video" "english\Unit 1_ LIVING IN URBAN AREAS\quiz" "english\Unit 1_ LIVING IN URBAN AREAS\exam" "english\Unit 1_ LIVING IN URBAN AREAS\past_paper" "english\Unit 1_ LIVING IN URBAN AREAS\short_note" "english\Unit 1_ LIVING IN URBAN AREAS\flashcard"
mkdir "english\Unit 2_ STUDY SKILLS\video" "english\Unit 2_ STUDY SKILLS\quiz" "english\Unit 2_ STUDY SKILLS\exam" "english\Unit 2_ STUDY SKILLS\past_paper" "english\Unit 2_ STUDY SKILLS\short_note" "english\Unit 2_ STUDY SKILLS\flashcard"
mkdir "english\Unit 3_ TRAFFIC ACCIDENT\video" "english\Unit 3_ TRAFFIC ACCIDENT\quiz" "english\Unit 3_ TRAFFIC ACCIDENT\exam" "english\Unit 3_ TRAFFIC ACCIDENT\past_paper" "english\Unit 3_ TRAFFIC ACCIDENT\short_note" "english\Unit 3_ TRAFFIC ACCIDENT\flashcard"
mkdir "english\Unit 4_ NATIONAL PARKS\video" "english\Unit 4_ NATIONAL PARKS\quiz" "english\Unit 4_ NATIONAL PARKS\exam" "english\Unit 4_ NATIONAL PARKS\past_paper" "english\Unit 4_ NATIONAL PARKS\short_note" "english\Unit 4_ NATIONAL PARKS\flashcard"
mkdir "english\Unit 5_ HORTICULTURE\video" "english\Unit 5_ HORTICULTURE\quiz" "english\Unit 5_ HORTICULTURE\exam" "english\Unit 5_ HORTICULTURE\past_paper" "english\Unit 5_ HORTICULTURE\short_note" "english\Unit 5_ HORTICULTURE\flashcard"
mkdir "english\Unit 6_ POVERTY IN ETHIOPIA\video" "english\Unit 6_ POVERTY IN ETHIOPIA\quiz" "english\Unit 6_ POVERTY IN ETHIOPIA\exam" "english\Unit 6_ POVERTY IN ETHIOPIA\past_paper" "english\Unit 6_ POVERTY IN ETHIOPIA\short_note" "english\Unit 6_ POVERTY IN ETHIOPIA\flashcard"
mkdir "english\Unit 7_ COMMUNITY SERVICES\video" "english\Unit 7_ COMMUNITY SERVICES\quiz" "english\Unit 7_ COMMUNITY SERVICES\exam" "english\Unit 7_ COMMUNITY SERVICES\past_paper" "english\Unit 7_ COMMUNITY SERVICES\short_note" "english\Unit 7_ COMMUNITY SERVICES\flashcard"
mkdir "english\Unit 8_ COMMUNICABLE DISEASES\video" "english\Unit 8_ COMMUNICABLE DISEASES\quiz" "english\Unit 8_ COMMUNICABLE DISEASES\exam" "english\Unit 8_ COMMUNICABLE DISEASES\past_paper" "english\Unit 8_ COMMUNICABLE DISEASES\short_note" "english\Unit 8_ COMMUNICABLE DISEASES\flashcard"

echo Grade 9 folder structure completed!
pause