@echo off
echo Creating Grade 10 folder structure with subfolders...

mkdir "Grade_10"
cd "Grade_10"

mkdir mathematics physics chemistry biology economics history geography citizenship it english

REM ========== MATHEMATICS ==========
mkdir "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\video" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\quiz" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\exam" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\past_paper" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\short_note" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\flashcard"
mkdir "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\video" "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\quiz" "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\exam" "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\past_paper" "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\short_note" "mathematics\Unit 2_ POLYNOMIAL FUNCTIONS\flashcard"
mkdir "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\video" "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\quiz" "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\exam" "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\past_paper" "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\short_note" "mathematics\Unit 3_ EXPONENTIAL AND LOGARITHMIC FUNCTIONS\flashcard"
mkdir "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\video" "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\quiz" "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\exam" "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\past_paper" "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\short_note" "mathematics\Unit 4_ TRIGONOMETRIC FUNCTIONS\flashcard"
mkdir "mathematics\Unit 5_ CIRCLES\video" "mathematics\Unit 5_ CIRCLES\quiz" "mathematics\Unit 5_ CIRCLES\exam" "mathematics\Unit 5_ CIRCLES\past_paper" "mathematics\Unit 5_ CIRCLES\short_note" "mathematics\Unit 5_ CIRCLES\flashcard"
mkdir "mathematics\Unit 6_ SOLID FIGURES\video" "mathematics\Unit 6_ SOLID FIGURES\quiz" "mathematics\Unit 6_ SOLID FIGURES\exam" "mathematics\Unit 6_ SOLID FIGURES\past_paper" "mathematics\Unit 6_ SOLID FIGURES\short_note" "mathematics\Unit 6_ SOLID FIGURES\flashcard"
mkdir "mathematics\Unit 7_ COORDINATE GEOMETRY\video" "mathematics\Unit 7_ COORDINATE GEOMETRY\quiz" "mathematics\Unit 7_ COORDINATE GEOMETRY\exam" "mathematics\Unit 7_ COORDINATE GEOMETRY\past_paper" "mathematics\Unit 7_ COORDINATE GEOMETRY\short_note" "mathematics\Unit 7_ COORDINATE GEOMETRY\flashcard"

REM ========== PHYSICS ==========
mkdir "physics\Unit 1_ VECTOR QUANTITIES\video" "physics\Unit 1_ VECTOR QUANTITIES\quiz" "physics\Unit 1_ VECTOR QUANTITIES\exam" "physics\Unit 1_ VECTOR QUANTITIES\past_paper" "physics\Unit 1_ VECTOR QUANTITIES\short_note" "physics\Unit 1_ VECTOR QUANTITIES\flashcard"
mkdir "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\video" "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\quiz" "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\exam" "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\past_paper" "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\short_note" "physics\Unit 2_ UNIFORMLY ACCELERATED MOTION\flashcard"
mkdir "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\video" "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\quiz" "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\exam" "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\past_paper" "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\short_note" "physics\Unit 3_ ELASTICITY AND STATIC EQUILIBRIUM OF RIGID BODY\flashcard"
mkdir "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\video" "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\quiz" "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\exam" "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\past_paper" "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\short_note" "physics\Unit 4_ STATIC AND CURRENT ELECTRICITY\flashcard"
mkdir "physics\Unit 5_ MAGNETISM\video" "physics\Unit 5_ MAGNETISM\quiz" "physics\Unit 5_ MAGNETISM\exam" "physics\Unit 5_ MAGNETISM\past_paper" "physics\Unit 5_ MAGNETISM\short_note" "physics\Unit 5_ MAGNETISM\flashcard"
mkdir "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\video" "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\quiz" "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\exam" "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\past_paper" "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\short_note" "physics\Unit 6_ ELECTROMAGNETIC WAVES AND GEOMETRICAL OPTICS\flashcard"

REM ========== CHEMISTRY ==========
mkdir "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\video" "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\quiz" "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\exam" "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\past_paper" "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\short_note" "chemistry\Unit 1_ CHEMICAL REACTIONS AND STOICHIOMETRY\flashcard"
mkdir "chemistry\Unit 2_ SOLUTIONS\video" "chemistry\Unit 2_ SOLUTIONS\quiz" "chemistry\Unit 2_ SOLUTIONS\exam" "chemistry\Unit 2_ SOLUTIONS\past_paper" "chemistry\Unit 2_ SOLUTIONS\short_note" "chemistry\Unit 2_ SOLUTIONS\flashcard"
mkdir "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\video" "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\quiz" "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\exam" "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\past_paper" "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\short_note" "chemistry\Unit 3_ IMPORTANT INORGANIC COMPOUNDS\flashcard"
mkdir "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\video" "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\quiz" "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\exam" "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\past_paper" "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\short_note" "chemistry\Unit 4_ ENERGY CHANGES AND ELECTROCHEMISTRY\flashcard"
mkdir "chemistry\Unit 5_ METALS AND NONMETALS\video" "chemistry\Unit 5_ METALS AND NONMETALS\quiz" "chemistry\Unit 5_ METALS AND NONMETALS\exam" "chemistry\Unit 5_ METALS AND NONMETALS\past_paper" "chemistry\Unit 5_ METALS AND NONMETALS\short_note" "chemistry\Unit 5_ METALS AND NONMETALS\flashcard"
mkdir "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\video" "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\quiz" "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\exam" "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\past_paper" "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\short_note" "chemistry\Unit 6_ HYDROCARBONS AND THEIR NATURAL SOURCES\flashcard"

REM ========== BIOLOGY ==========
mkdir "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\video" "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\quiz" "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\exam" "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\past_paper" "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\short_note" "biology\Unit 1_ SUB-FIELDS OF BIOLOGY\flashcard"
mkdir "biology\Unit 2_ PLANTS\video" "biology\Unit 2_ PLANTS\quiz" "biology\Unit 2_ PLANTS\exam" "biology\Unit 2_ PLANTS\past_paper" "biology\Unit 2_ PLANTS\short_note" "biology\Unit 2_ PLANTS\flashcard"
mkdir "biology\Unit 3_ BIOCHEMICAL MOLECULES\video" "biology\Unit 3_ BIOCHEMICAL MOLECULES\quiz" "biology\Unit 3_ BIOCHEMICAL MOLECULES\exam" "biology\Unit 3_ BIOCHEMICAL MOLECULES\past_paper" "biology\Unit 3_ BIOCHEMICAL MOLECULES\short_note" "biology\Unit 3_ BIOCHEMICAL MOLECULES\flashcard"
mkdir "biology\Unit 4_ CELL REPRODUCTION\video" "biology\Unit 4_ CELL REPRODUCTION\quiz" "biology\Unit 4_ CELL REPRODUCTION\exam" "biology\Unit 4_ CELL REPRODUCTION\past_paper" "biology\Unit 4_ CELL REPRODUCTION\short_note" "biology\Unit 4_ CELL REPRODUCTION\flashcard"
mkdir "biology\Unit 5_ HUMAN BIOLOGY\video" "biology\Unit 5_ HUMAN BIOLOGY\quiz" "biology\Unit 5_ HUMAN BIOLOGY\exam" "biology\Unit 5_ HUMAN BIOLOGY\past_paper" "biology\Unit 5_ HUMAN BIOLOGY\short_note" "biology\Unit 5_ HUMAN BIOLOGY\flashcard"
mkdir "biology\Unit 6_ ECOLOGICAL INTERACTION\video" "biology\Unit 6_ ECOLOGICAL INTERACTION\quiz" "biology\Unit 6_ ECOLOGICAL INTERACTION\exam" "biology\Unit 6_ ECOLOGICAL INTERACTION\past_paper" "biology\Unit 6_ ECOLOGICAL INTERACTION\short_note" "biology\Unit 6_ ECOLOGICAL INTERACTION\flashcard"

REM ========== ECONOMICS ==========
mkdir "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\video" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\quiz" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\exam" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\past_paper" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\short_note" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOUR\flashcard"
mkdir "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\video" "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\quiz" "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\exam" "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\past_paper" "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\short_note" "economics\Unit 2_ THEORIES OF DEMAND AND SUPPLY\flashcard"
mkdir "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\video" "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\quiz" "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\exam" "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\past_paper" "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\short_note" "economics\Unit 3_ THEORIES OF PRODUCTION AND COST\flashcard"
mkdir "economics\Unit 4_ MARKET STRUCTURE\video" "economics\Unit 4_ MARKET STRUCTURE\quiz" "economics\Unit 4_ MARKET STRUCTURE\exam" "economics\Unit 4_ MARKET STRUCTURE\past_paper" "economics\Unit 4_ MARKET STRUCTURE\short_note" "economics\Unit 4_ MARKET STRUCTURE\flashcard"
mkdir "economics\Unit 5_ BANKING AND FINANCE\video" "economics\Unit 5_ BANKING AND FINANCE\quiz" "economics\Unit 5_ BANKING AND FINANCE\exam" "economics\Unit 5_ BANKING AND FINANCE\past_paper" "economics\Unit 5_ BANKING AND FINANCE\short_note" "economics\Unit 5_ BANKING AND FINANCE\flashcard"
mkdir "economics\Unit 6_ ECONOMIC GROWTH\video" "economics\Unit 6_ ECONOMIC GROWTH\quiz" "economics\Unit 6_ ECONOMIC GROWTH\exam" "economics\Unit 6_ ECONOMIC GROWTH\past_paper" "economics\Unit 6_ ECONOMIC GROWTH\short_note" "economics\Unit 6_ ECONOMIC GROWTH\flashcard"
mkdir "economics\Unit 7_ THE ETHIOPIAN ECONOMY\video" "economics\Unit 7_ THE ETHIOPIAN ECONOMY\quiz" "economics\Unit 7_ THE ETHIOPIAN ECONOMY\exam" "economics\Unit 7_ THE ETHIOPIAN ECONOMY\past_paper" "economics\Unit 7_ THE ETHIOPIAN ECONOMY\short_note" "economics\Unit 7_ THE ETHIOPIAN ECONOMY\flashcard"
mkdir "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\video" "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\quiz" "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\exam" "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\past_paper" "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\short_note" "economics\Unit 8_ BUSINESS STARTUPS AND INNOVATION\flashcard"

REM ========== HISTORY (CORRECTED - No Colons) ==========
mkdir "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\video" "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\quiz" "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\exam" "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\past_paper" "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\short_note" "history\Unit 1_ DEVELOPMENT OF CAPITALISM AND NATIONALISM 1815-1914\flashcard"
mkdir "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\video" "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\quiz" "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\exam" "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\past_paper" "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\short_note" "history\Unit 2_ AFRICA AND THE COLONIAL EXPERIENCE (1880s-1960s)\flashcard"
mkdir "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\video" "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\quiz" "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\exam" "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\past_paper" "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\short_note" "history\Unit 3_ SOCIAL, ECONOMIC AND POLITICAL DEVELOPMENTS IN ETHIOPIA MID 19th C TO 1941\flashcard"
mkdir "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\video" "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\quiz" "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\exam" "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\past_paper" "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\short_note" "history\Unit 4_ SOCIETY AND POLITICS IN THE AGE OF WORLD WARS 1914-1945\flashcard"
mkdir "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\video" "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\quiz" "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\exam" "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\past_paper" "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\short_note" "history\Unit 5_ GLOBAL AND REGIONAL DEVELOPMENTS SINCE 1945\flashcard"
mkdir "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\video" "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\quiz" "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\exam" "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\past_paper" "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\short_note" "history\Unit 6_ ETHIOPIA INTERNAL DEVELOPMENTS AND EXTERNAL INFLUENCES FROM 1941 TO 1991\flashcard"
mkdir "history\Unit 7_ AFRICA SINCE 1960\video" "history\Unit 7_ AFRICA SINCE 1960\quiz" "history\Unit 7_ AFRICA SINCE 1960\exam" "history\Unit 7_ AFRICA SINCE 1960\past_paper" "history\Unit 7_ AFRICA SINCE 1960\short_note" "history\Unit 7_ AFRICA SINCE 1960\flashcard"
mkdir "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\video" "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\quiz" "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\exam" "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\past_paper" "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\short_note" "history\Unit 8_ POST-1991 DEVELOPMENTS IN ETHIOPIA\flashcard"
mkdir "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\video" "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\quiz" "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\exam" "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\past_paper" "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\short_note" "history\Unit 9_ INDIGENOUS KNOWLEDGE AND HERITAGES OF ETHIOPIA\flashcard"

REM ========== GEOGRAPHY ==========
mkdir "geography\Unit 1_ LANDFORMS OF AFRICA\video" "geography\Unit 1_ LANDFORMS OF AFRICA\quiz" "geography\Unit 1_ LANDFORMS OF AFRICA\exam" "geography\Unit 1_ LANDFORMS OF AFRICA\past_paper" "geography\Unit 1_ LANDFORMS OF AFRICA\short_note" "geography\Unit 1_ LANDFORMS OF AFRICA\flashcard"
mkdir "geography\Unit 2_ CLIMATE OF AFRICA\video" "geography\Unit 2_ CLIMATE OF AFRICA\quiz" "geography\Unit 2_ CLIMATE OF AFRICA\exam" "geography\Unit 2_ CLIMATE OF AFRICA\past_paper" "geography\Unit 2_ CLIMATE OF AFRICA\short_note" "geography\Unit 2_ CLIMATE OF AFRICA\flashcard"
mkdir "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\video" "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\quiz" "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\exam" "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\past_paper" "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\short_note" "geography\Unit 3_ NATURAL RESOURCE BASE OF AFRICA\flashcard"
mkdir "geography\Unit 4_ POPULATION OF AFRICA\video" "geography\Unit 4_ POPULATION OF AFRICA\quiz" "geography\Unit 4_ POPULATION OF AFRICA\exam" "geography\Unit 4_ POPULATION OF AFRICA\past_paper" "geography\Unit 4_ POPULATION OF AFRICA\short_note" "geography\Unit 4_ POPULATION OF AFRICA\flashcard"
mkdir "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\video" "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\quiz" "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\exam" "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\past_paper" "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\short_note" "geography\Unit 5_ MAJOR ECONOMIC AND CULTURAL ACTIVITIES OF AFRICA\flashcard"
mkdir "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\video" "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\quiz" "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\exam" "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\past_paper" "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\short_note" "geography\Unit 6_ HUMAN NATURAL ENVIRONMENT INTERACTIONS\flashcard"
mkdir "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\video" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\quiz" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\exam" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\past_paper" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\short_note" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS IN AFRICA\flashcard"
mkdir "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\video" "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\quiz" "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\exam" "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\past_paper" "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\short_note" "geography\Unit 8_ GEOSPATIAL INFORMATION AND DATA PROCESSING\flashcard"

REM ========== CITIZENSHIP ==========
mkdir "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\video" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\quiz" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\exam" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\past_paper" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\short_note" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\flashcard"
mkdir "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\video" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\quiz" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\exam" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\past_paper" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\short_note" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\flashcard"
mkdir "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\video" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\quiz" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\exam" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\past_paper" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\short_note" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\flashcard"
mkdir "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\video" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\quiz" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\exam" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\past_paper" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\short_note" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\flashcard"
mkdir "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\video" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\quiz" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\exam" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\past_paper" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\short_note" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\flashcard"
mkdir "citizenship\Unit 6_ HUMAN RIGHTS\video" "citizenship\Unit 6_ HUMAN RIGHTS\quiz" "citizenship\Unit 6_ HUMAN RIGHTS\exam" "citizenship\Unit 6_ HUMAN RIGHTS\past_paper" "citizenship\Unit 6_ HUMAN RIGHTS\short_note" "citizenship\Unit 6_ HUMAN RIGHTS\flashcard"
mkdir "citizenship\Unit 7_ PATRIOTISM\video" "citizenship\Unit 7_ PATRIOTISM\quiz" "citizenship\Unit 7_ PATRIOTISM\exam" "citizenship\Unit 7_ PATRIOTISM\past_paper" "citizenship\Unit 7_ PATRIOTISM\short_note" "citizenship\Unit 7_ PATRIOTISM\flashcard"
mkdir "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\video" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\quiz" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\exam" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\past_paper" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\short_note" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\flashcard"

REM ========== IT ==========
mkdir "it\Unit 1_ ORGANIZATION OF FILES\video" "it\Unit 1_ ORGANIZATION OF FILES\quiz" "it\Unit 1_ ORGANIZATION OF FILES\exam" "it\Unit 1_ ORGANIZATION OF FILES\past_paper" "it\Unit 1_ ORGANIZATION OF FILES\short_note" "it\Unit 1_ ORGANIZATION OF FILES\flashcard"
mkdir "it\Unit 2_ COMPUTER NETWORK\video" "it\Unit 2_ COMPUTER NETWORK\quiz" "it\Unit 2_ COMPUTER NETWORK\exam" "it\Unit 2_ COMPUTER NETWORK\past_paper" "it\Unit 2_ COMPUTER NETWORK\short_note" "it\Unit 2_ COMPUTER NETWORK\flashcard"
mkdir "it\Unit 3_ APPLICATION SOFTWARE\video" "it\Unit 3_ APPLICATION SOFTWARE\quiz" "it\Unit 3_ APPLICATION SOFTWARE\exam" "it\Unit 3_ APPLICATION SOFTWARE\past_paper" "it\Unit 3_ APPLICATION SOFTWARE\short_note" "it\Unit 3_ APPLICATION SOFTWARE\flashcard"
mkdir "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\video" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\quiz" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\exam" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\past_paper" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\short_note" "it\Unit 4_ IMAGE PROCESSING AND MULTIMEDIA\flashcard"
mkdir "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\video" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\quiz" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\exam" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\past_paper" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\short_note" "it\Unit 5_ INFORMATION AND COMPUTER SECURITY\flashcard"
mkdir "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\video" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\quiz" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\exam" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\past_paper" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\short_note" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Unit 1_ POPULATION GROWTH\video" "english\Unit 1_ POPULATION GROWTH\quiz" "english\Unit 1_ POPULATION GROWTH\exam" "english\Unit 1_ POPULATION GROWTH\past_paper" "english\Unit 1_ POPULATION GROWTH\short_note" "english\Unit 1_ POPULATION GROWTH\flashcard"
mkdir "english\Unit 2_ TRAVEL BEHAVIORS\video" "english\Unit 2_ TRAVEL BEHAVIORS\quiz" "english\Unit 2_ TRAVEL BEHAVIORS\exam" "english\Unit 2_ TRAVEL BEHAVIORS\past_paper" "english\Unit 2_ TRAVEL BEHAVIORS\short_note" "english\Unit 2_ TRAVEL BEHAVIORS\flashcard"
mkdir "english\Unit 3_ PUNCTUALITY\video" "english\Unit 3_ PUNCTUALITY\quiz" "english\Unit 3_ PUNCTUALITY\exam" "english\Unit 3_ PUNCTUALITY\past_paper" "english\Unit 3_ PUNCTUALITY\short_note" "english\Unit 3_ PUNCTUALITY\flashcard"
mkdir "english\Unit 4_ TOURIST ATTRACTIONS\video" "english\Unit 4_ TOURIST ATTRACTIONS\quiz" "english\Unit 4_ TOURIST ATTRACTIONS\exam" "english\Unit 4_ TOURIST ATTRACTIONS\past_paper" "english\Unit 4_ TOURIST ATTRACTIONS\short_note" "english\Unit 4_ TOURIST ATTRACTIONS\flashcard"
mkdir "english\Unit 5_ HONEY PROCESSING\video" "english\Unit 5_ HONEY PROCESSING\quiz" "english\Unit 5_ HONEY PROCESSING\exam" "english\Unit 5_ HONEY PROCESSING\past_paper" "english\Unit 5_ HONEY PROCESSING\short_note" "english\Unit 5_ HONEY PROCESSING\flashcard"
mkdir "english\Unit 6_ MIGRATION\video" "english\Unit 6_ MIGRATION\quiz" "english\Unit 6_ MIGRATION\exam" "english\Unit 6_ MIGRATION\past_paper" "english\Unit 6_ MIGRATION\short_note" "english\Unit 6_ MIGRATION\flashcard"
mkdir "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\video" "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\quiz" "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\exam" "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\past_paper" "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\short_note" "english\Unit 7_ BRANDING ETHIOPIA AND NATIONAL IDENTITY\flashcard"
mkdir "english\Unit 8_ THE HEALING POWER OF PLANTS\video" "english\Unit 8_ THE HEALING POWER OF PLANTS\quiz" "english\Unit 8_ THE HEALING POWER OF PLANTS\exam" "english\Unit 8_ THE HEALING POWER OF PLANTS\past_paper" "english\Unit 8_ THE HEALING POWER OF PLANTS\short_note" "english\Unit 8_ THE HEALING POWER OF PLANTS\flashcard"
mkdir "english\Unit 9_ MULTILINGUALISM\video" "english\Unit 9_ MULTILINGUALISM\quiz" "english\Unit 9_ MULTILINGUALISM\exam" "english\Unit 9_ MULTILINGUALISM\past_paper" "english\Unit 9_ MULTILINGUALISM\short_note" "english\Unit 9_ MULTILINGUALISM\flashcard"
mkdir "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\video" "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\quiz" "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\exam" "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\past_paper" "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\short_note" "english\Unit 10_ DIGITAL VS SATELLITE TELEVISION\flashcard"

echo Grade 10 folder structure completed!
pause