@echo off
echo Creating Natural Science folder structure with subfolders...

mkdir "Natural_Science"
cd "Natural_Science"

mkdir mathematics physics english logic psychology geography

REM ========== MATHEMATICS ==========
mkdir "mathematics\Chapter 1_ propositional logic and set theory\video" "mathematics\Chapter 1_ propositional logic and set theory\quiz" "mathematics\Chapter 1_ propositional logic and set theory\exam" "mathematics\Chapter 1_ propositional logic and set theory\past_paper" "mathematics\Chapter 1_ propositional logic and set theory\short_note" "mathematics\Chapter 1_ propositional logic and set theory\flashcard"
mkdir "mathematics\Chapter 2_ the real and complex number system\video" "mathematics\Chapter 2_ the real and complex number system\quiz" "mathematics\Chapter 2_ the real and complex number system\exam" "mathematics\Chapter 2_ the real and complex number system\past_paper" "mathematics\Chapter 2_ the real and complex number system\short_note" "mathematics\Chapter 2_ the real and complex number system\flashcard"
mkdir "mathematics\Chapter 3_ function\video" "mathematics\Chapter 3_ function\quiz" "mathematics\Chapter 3_ function\exam" "mathematics\Chapter 3_ function\past_paper" "mathematics\Chapter 3_ function\short_note" "mathematics\Chapter 3_ function\flashcard"
mkdir "mathematics\Chapter 4_ analytic geometry\video" "mathematics\Chapter 4_ analytic geometry\quiz" "mathematics\Chapter 4_ analytic geometry\exam" "mathematics\Chapter 4_ analytic geometry\past_paper" "mathematics\Chapter 4_ analytic geometry\short_note" "mathematics\Chapter 4_ analytic geometry\flashcard"

REM ========== PHYSICS ==========
mkdir "physics\Chapter 1_ preliminaries\video" "physics\Chapter 1_ preliminaries\quiz" "physics\Chapter 1_ preliminaries\exam" "physics\Chapter 1_ preliminaries\past_paper" "physics\Chapter 1_ preliminaries\short_note" "physics\Chapter 1_ preliminaries\flashcard"
mkdir "physics\Chapter 2_ kinematic and dynamic of particles\video" "physics\Chapter 2_ kinematic and dynamic of particles\quiz" "physics\Chapter 2_ kinematic and dynamic of particles\exam" "physics\Chapter 2_ kinematic and dynamic of particles\past_paper" "physics\Chapter 2_ kinematic and dynamic of particles\short_note" "physics\Chapter 2_ kinematic and dynamic of particles\flashcard"
mkdir "physics\Chapter 3_ fluid dynamics\video" "physics\Chapter 3_ fluid dynamics\quiz" "physics\Chapter 3_ fluid dynamics\exam" "physics\Chapter 3_ fluid dynamics\past_paper" "physics\Chapter 3_ fluid dynamics\short_note" "physics\Chapter 3_ fluid dynamics\flashcard"
mkdir "physics\Chapter 4_ heat and thermodynamics\video" "physics\Chapter 4_ heat and thermodynamics\quiz" "physics\Chapter 4_ heat and thermodynamics\exam" "physics\Chapter 4_ heat and thermodynamics\past_paper" "physics\Chapter 4_ heat and thermodynamics\short_note" "physics\Chapter 4_ heat and thermodynamics\flashcard"
mkdir "physics\Chapter 5_ oscillation, waves and optics\video" "physics\Chapter 5_ oscillation, waves and optics\quiz" "physics\Chapter 5_ oscillation, waves and optics\exam" "physics\Chapter 5_ oscillation, waves and optics\past_paper" "physics\Chapter 5_ oscillation, waves and optics\short_note" "physics\Chapter 5_ oscillation, waves and optics\flashcard"
mkdir "physics\Chapter 6_ electromagnetism and electronics\video" "physics\Chapter 6_ electromagnetism and electronics\quiz" "physics\Chapter 6_ electromagnetism and electronics\exam" "physics\Chapter 6_ electromagnetism and electronics\past_paper" "physics\Chapter 6_ electromagnetism and electronics\short_note" "physics\Chapter 6_ electromagnetism and electronics\flashcard"
mkdir "physics\Chapter 7_ cross cutting application of physics\video" "physics\Chapter 7_ cross cutting application of physics\quiz" "physics\Chapter 7_ cross cutting application of physics\exam" "physics\Chapter 7_ cross cutting application of physics\past_paper" "physics\Chapter 7_ cross cutting application of physics\short_note" "physics\Chapter 7_ cross cutting application of physics\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Chapter 1_ study skills\video" "english\Chapter 1_ study skills\quiz" "english\Chapter 1_ study skills\exam" "english\Chapter 1_ study skills\past_paper" "english\Chapter 1_ study skills\short_note" "english\Chapter 1_ study skills\flashcard"
mkdir "english\Chapter 2_ health and fitness\video" "english\Chapter 2_ health and fitness\quiz" "english\Chapter 2_ health and fitness\exam" "english\Chapter 2_ health and fitness\past_paper" "english\Chapter 2_ health and fitness\short_note" "english\Chapter 2_ health and fitness\flashcard"
mkdir "english\Chapter 3_ cultural values\video" "english\Chapter 3_ cultural values\quiz" "english\Chapter 3_ cultural values\exam" "english\Chapter 3_ cultural values\past_paper" "english\Chapter 3_ cultural values\short_note" "english\Chapter 3_ cultural values\flashcard"
mkdir "english\Chapter 4_ wild life\video" "english\Chapter 4_ wild life\quiz" "english\Chapter 4_ wild life\exam" "english\Chapter 4_ wild life\past_paper" "english\Chapter 4_ wild life\short_note" "english\Chapter 4_ wild life\flashcard"
mkdir "english\Chapter 5_ population\video" "english\Chapter 5_ population\quiz" "english\Chapter 5_ population\exam" "english\Chapter 5_ population\past_paper" "english\Chapter 5_ population\short_note" "english\Chapter 5_ population\flashcard"

REM ========== LOGIC ==========
mkdir "logic\Chapter 1_ introduction to philosophy\video" "logic\Chapter 1_ introduction to philosophy\quiz" "logic\Chapter 1_ introduction to philosophy\exam" "logic\Chapter 1_ introduction to philosophy\past_paper" "logic\Chapter 1_ introduction to philosophy\short_note" "logic\Chapter 1_ introduction to philosophy\flashcard"
mkdir "logic\Chapter 2_ basic concept of logic\video" "logic\Chapter 2_ basic concept of logic\quiz" "logic\Chapter 2_ basic concept of logic\exam" "logic\Chapter 2_ basic concept of logic\past_paper" "logic\Chapter 2_ basic concept of logic\short_note" "logic\Chapter 2_ basic concept of logic\flashcard"
mkdir "logic\Chapter 3_ logic and language\video" "logic\Chapter 3_ logic and language\quiz" "logic\Chapter 3_ logic and language\exam" "logic\Chapter 3_ logic and language\past_paper" "logic\Chapter 3_ logic and language\short_note" "logic\Chapter 3_ logic and language\flashcard"
mkdir "logic\Chapter 4_ basic concepts of critical thinking\video" "logic\Chapter 4_ basic concepts of critical thinking\quiz" "logic\Chapter 4_ basic concepts of critical thinking\exam" "logic\Chapter 4_ basic concepts of critical thinking\past_paper" "logic\Chapter 4_ basic concepts of critical thinking\short_note" "logic\Chapter 4_ basic concepts of critical thinking\flashcard"
mkdir "logic\Chapter 5_ informal fallacies\video" "logic\Chapter 5_ informal fallacies\quiz" "logic\Chapter 5_ informal fallacies\exam" "logic\Chapter 5_ informal fallacies\past_paper" "logic\Chapter 5_ informal fallacies\short_note" "logic\Chapter 5_ informal fallacies\flashcard"
mkdir "logic\Chapter 6_ categorical propositions\video" "logic\Chapter 6_ categorical propositions\quiz" "logic\Chapter 6_ categorical propositions\exam" "logic\Chapter 6_ categorical propositions\past_paper" "logic\Chapter 6_ categorical propositions\short_note" "logic\Chapter 6_ categorical propositions\flashcard"

REM ========== PSYCHOLOGY ==========
mkdir "psychology\Chapter 1_ essence of psychology\video" "psychology\Chapter 1_ essence of psychology\quiz" "psychology\Chapter 1_ essence of psychology\exam" "psychology\Chapter 1_ essence of psychology\past_paper" "psychology\Chapter 1_ essence of psychology\short_note" "psychology\Chapter 1_ essence of psychology\flashcard"
mkdir "psychology\Chapter 2_ sensation and perception\video" "psychology\Chapter 2_ sensation and perception\quiz" "psychology\Chapter 2_ sensation and perception\exam" "psychology\Chapter 2_ sensation and perception\past_paper" "psychology\Chapter 2_ sensation and perception\short_note" "psychology\Chapter 2_ sensation and perception\flashcard"
mkdir "psychology\Chapter 3_ leaning and theories of learning\video" "psychology\Chapter 3_ leaning and theories of learning\quiz" "psychology\Chapter 3_ leaning and theories of learning\exam" "psychology\Chapter 3_ leaning and theories of learning\past_paper" "psychology\Chapter 3_ leaning and theories of learning\short_note" "psychology\Chapter 3_ leaning and theories of learning\flashcard"
mkdir "psychology\Chapter 4_ memory and forgetting\video" "psychology\Chapter 4_ memory and forgetting\quiz" "psychology\Chapter 4_ memory and forgetting\exam" "psychology\Chapter 4_ memory and forgetting\past_paper" "psychology\Chapter 4_ memory and forgetting\short_note" "psychology\Chapter 4_ memory and forgetting\flashcard"
mkdir "psychology\Chapter 5_ motivation and emotion\video" "psychology\Chapter 5_ motivation and emotion\quiz" "psychology\Chapter 5_ motivation and emotion\exam" "psychology\Chapter 5_ motivation and emotion\past_paper" "psychology\Chapter 5_ motivation and emotion\short_note" "psychology\Chapter 5_ motivation and emotion\flashcard"
mkdir "psychology\Chapter 6_ personality\video" "psychology\Chapter 6_ personality\quiz" "psychology\Chapter 6_ personality\exam" "psychology\Chapter 6_ personality\past_paper" "psychology\Chapter 6_ personality\short_note" "psychology\Chapter 6_ personality\flashcard"
mkdir "psychology\Chapter 7_ psychological disorder and treatment techniques\video" "psychology\Chapter 7_ psychological disorder and treatment techniques\quiz" "psychology\Chapter 7_ psychological disorder and treatment techniques\exam" "psychology\Chapter 7_ psychological disorder and treatment techniques\past_paper" "psychology\Chapter 7_ psychological disorder and treatment techniques\short_note" "psychology\Chapter 7_ psychological disorder and treatment techniques\flashcard"
mkdir "psychology\Chapter 8_ intro to life skills\video" "psychology\Chapter 8_ intro to life skills\quiz" "psychology\Chapter 8_ intro to life skills\exam" "psychology\Chapter 8_ intro to life skills\past_paper" "psychology\Chapter 8_ intro to life skills\short_note" "psychology\Chapter 8_ intro to life skills\flashcard"
mkdir "psychology\Chapter 9_ inta-personal and interpersonal skills\video" "psychology\Chapter 9_ inta-personal and interpersonal skills\quiz" "psychology\Chapter 9_ inta-personal and interpersonal skills\exam" "psychology\Chapter 9_ inta-personal and interpersonal skills\past_paper" "psychology\Chapter 9_ inta-personal and interpersonal skills\short_note" "psychology\Chapter 9_ inta-personal and interpersonal skills\flashcard"
mkdir "psychology\Chapter 10_ academic skills\video" "psychology\Chapter 10_ academic skills\quiz" "psychology\Chapter 10_ academic skills\exam" "psychology\Chapter 10_ academic skills\past_paper" "psychology\Chapter 10_ academic skills\short_note" "psychology\Chapter 10_ academic skills\flashcard"
mkdir "psychology\Chapter 11_ social skills\video" "psychology\Chapter 11_ social skills\quiz" "psychology\Chapter 11_ social skills\exam" "psychology\Chapter 11_ social skills\past_paper" "psychology\Chapter 11_ social skills\short_note" "psychology\Chapter 11_ social skills\flashcard"

REM ========== GEOGRAPHY ==========
mkdir "geography\Chapter 1_ introduction\video" "geography\Chapter 1_ introduction\quiz" "geography\Chapter 1_ introduction\exam" "geography\Chapter 1_ introduction\past_paper" "geography\Chapter 1_ introduction\short_note" "geography\Chapter 1_ introduction\flashcard"
mkdir "geography\Chapter 2_ the geology of Ethiopia and the horn\video" "geography\Chapter 2_ the geology of Ethiopia and the horn\quiz" "geography\Chapter 2_ the geology of Ethiopia and the horn\exam" "geography\Chapter 2_ the geology of Ethiopia and the horn\past_paper" "geography\Chapter 2_ the geology of Ethiopia and the horn\short_note" "geography\Chapter 2_ the geology of Ethiopia and the horn\flashcard"
mkdir "geography\Chapter 3_ the topography of Ethiopia and the horn\video" "geography\Chapter 3_ the topography of Ethiopia and the horn\quiz" "geography\Chapter 3_ the topography of Ethiopia and the horn\exam" "geography\Chapter 3_ the topography of Ethiopia and the horn\past_paper" "geography\Chapter 3_ the topography of Ethiopia and the horn\short_note" "geography\Chapter 3_ the topography of Ethiopia and the horn\flashcard"
mkdir "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\video" "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\quiz" "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\exam" "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\past_paper" "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\short_note" "geography\Chapter 4_ drainage system and water resource of Ethiopia and the horn\flashcard"
mkdir "geography\Chapter 5_ the climate of Ethiopia and the horn\video" "geography\Chapter 5_ the climate of Ethiopia and the horn\quiz" "geography\Chapter 5_ the climate of Ethiopia and the horn\exam" "geography\Chapter 5_ the climate of Ethiopia and the horn\past_paper" "geography\Chapter 5_ the climate of Ethiopia and the horn\short_note" "geography\Chapter 5_ the climate of Ethiopia and the horn\flashcard"
mkdir "geography\Chapter 6_ soils, natural vegetation and wildlife resource\video" "geography\Chapter 6_ soils, natural vegetation and wildlife resource\quiz" "geography\Chapter 6_ soils, natural vegetation and wildlife resource\exam" "geography\Chapter 6_ soils, natural vegetation and wildlife resource\past_paper" "geography\Chapter 6_ soils, natural vegetation and wildlife resource\short_note" "geography\Chapter 6_ soils, natural vegetation and wildlife resource\flashcard"
mkdir "geography\Chapter 7_ population of ethiopia and the horn\video" "geography\Chapter 7_ population of ethiopia and the horn\quiz" "geography\Chapter 7_ population of ethiopia and the horn\exam" "geography\Chapter 7_ population of ethiopia and the horn\past_paper" "geography\Chapter 7_ population of ethiopia and the horn\short_note" "geography\Chapter 7_ population of ethiopia and the horn\flashcard"
mkdir "geography\Chapter 8_ economic activitie in Ethiopia\video" "geography\Chapter 8_ economic activitie in Ethiopia\quiz" "geography\Chapter 8_ economic activitie in Ethiopia\exam" "geography\Chapter 8_ economic activitie in Ethiopia\past_paper" "geography\Chapter 8_ economic activitie in Ethiopia\short_note" "geography\Chapter 8_ economic activitie in Ethiopia\flashcard"

echo Natural Science folder structure completed!
pause