@echo off
echo Creating Grade 12 Natural Science folder structure with subfolders...

mkdir "Grade_12_Natural_Science"
cd "Grade_12_Natural_Science"

mkdir mathematics physics chemistry biology it english agriculture aptitude

REM ========== MATHEMATICS ==========
mkdir "mathematics\Unit 1_ SEQUENCES AND SERIES\video" "mathematics\Unit 1_ SEQUENCES AND SERIES\quiz" "mathematics\Unit 1_ SEQUENCES AND SERIES\exam" "mathematics\Unit 1_ SEQUENCES AND SERIES\past_paper" "mathematics\Unit 1_ SEQUENCES AND SERIES\short_note" "mathematics\Unit 1_ SEQUENCES AND SERIES\flashcard"
mkdir "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\video" "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\quiz" "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\exam" "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\past_paper" "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\short_note" "mathematics\Unit 2_ INTRODUCTIONS TO CALCULUS\flashcard"
mkdir "mathematics\Unit 3_ STATISTICS\video" "mathematics\Unit 3_ STATISTICS\quiz" "mathematics\Unit 3_ STATISTICS\exam" "mathematics\Unit 3_ STATISTICS\past_paper" "mathematics\Unit 3_ STATISTICS\short_note" "mathematics\Unit 3_ STATISTICS\flashcard"
mkdir "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\video" "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\quiz" "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\exam" "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\past_paper" "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\short_note" "mathematics\Unit 4_ INTRODUCTION TO LINEAR PROGRAMMING\flashcard"
mkdir "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\video" "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\quiz" "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\exam" "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\past_paper" "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\short_note" "mathematics\Unit 5_ MATHEMATICAL APPLICATIONS IN BUSINESS\flashcard"

REM ========== PHYSICS ==========
mkdir "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\video" "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\quiz" "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\exam" "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\past_paper" "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\short_note" "physics\Unit 1_ APPLICATION OF PHYSICS IN OTHER FIELDS\flashcard"
mkdir "physics\Unit 2_ TWO-DIMENSIONAL MOTION\video" "physics\Unit 2_ TWO-DIMENSIONAL MOTION\quiz" "physics\Unit 2_ TWO-DIMENSIONAL MOTION\exam" "physics\Unit 2_ TWO-DIMENSIONAL MOTION\past_paper" "physics\Unit 2_ TWO-DIMENSIONAL MOTION\short_note" "physics\Unit 2_ TWO-DIMENSIONAL MOTION\flashcard"
mkdir "physics\Unit 3_ FLUID MECHANICS\video" "physics\Unit 3_ FLUID MECHANICS\quiz" "physics\Unit 3_ FLUID MECHANICS\exam" "physics\Unit 3_ FLUID MECHANICS\past_paper" "physics\Unit 3_ FLUID MECHANICS\short_note" "physics\Unit 3_ FLUID MECHANICS\flashcard"
mkdir "physics\Unit 4_ ELECTROMAGNETISM\video" "physics\Unit 4_ ELECTROMAGNETISM\quiz" "physics\Unit 4_ ELECTROMAGNETISM\exam" "physics\Unit 4_ ELECTROMAGNETISM\past_paper" "physics\Unit 4_ ELECTROMAGNETISM\short_note" "physics\Unit 4_ ELECTROMAGNETISM\flashcard"
mkdir "physics\Unit 5_ BASICS OF ELECTRONICS\video" "physics\Unit 5_ BASICS OF ELECTRONICS\quiz" "physics\Unit 5_ BASICS OF ELECTRONICS\exam" "physics\Unit 5_ BASICS OF ELECTRONICS\past_paper" "physics\Unit 5_ BASICS OF ELECTRONICS\short_note" "physics\Unit 5_ BASICS OF ELECTRONICS\flashcard"

REM ========== CHEMISTRY ==========
mkdir "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\video" "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\quiz" "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\exam" "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\past_paper" "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\short_note" "chemistry\Unit 1_ ACID-BASE CONCEPTS AND IONIC EQUILIBRIA\flashcard"
mkdir "chemistry\Unit 2_ ELECTROCHEMISTRY\video" "chemistry\Unit 2_ ELECTROCHEMISTRY\quiz" "chemistry\Unit 2_ ELECTROCHEMISTRY\exam" "chemistry\Unit 2_ ELECTROCHEMISTRY\past_paper" "chemistry\Unit 2_ ELECTROCHEMISTRY\short_note" "chemistry\Unit 2_ ELECTROCHEMISTRY\flashcard"
mkdir "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\video" "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\quiz" "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\exam" "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\past_paper" "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\short_note" "chemistry\Unit 3_ INDUSTRIAL CHEMISTRY\flashcard"
mkdir "chemistry\Unit 4_ POLYMERS\video" "chemistry\Unit 4_ POLYMERS\quiz" "chemistry\Unit 4_ POLYMERS\exam" "chemistry\Unit 4_ POLYMERS\past_paper" "chemistry\Unit 4_ POLYMERS\short_note" "chemistry\Unit 4_ POLYMERS\flashcard"
mkdir "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\video" "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\quiz" "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\exam" "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\past_paper" "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\short_note" "chemistry\Unit 5_ INTRODUCTION TO ENVIRONMENTAL CHEMISTRY\flashcard"

REM ========== BIOLOGY ==========
mkdir "biology\Unit 1_ APPLICATION OF BIOLOGY\video" "biology\Unit 1_ APPLICATION OF BIOLOGY\quiz" "biology\Unit 1_ APPLICATION OF BIOLOGY\exam" "biology\Unit 1_ APPLICATION OF BIOLOGY\past_paper" "biology\Unit 1_ APPLICATION OF BIOLOGY\short_note" "biology\Unit 1_ APPLICATION OF BIOLOGY\flashcard"
mkdir "biology\Unit 2_ MICROORGANISMS\video" "biology\Unit 2_ MICROORGANISMS\quiz" "biology\Unit 2_ MICROORGANISMS\exam" "biology\Unit 2_ MICROORGANISMS\past_paper" "biology\Unit 2_ MICROORGANISMS\short_note" "biology\Unit 2_ MICROORGANISMS\flashcard"
mkdir "biology\Unit 3_ ENERGY TRANSFORMATION\video" "biology\Unit 3_ ENERGY TRANSFORMATION\quiz" "biology\Unit 3_ ENERGY TRANSFORMATION\exam" "biology\Unit 3_ ENERGY TRANSFORMATION\past_paper" "biology\Unit 3_ ENERGY TRANSFORMATION\short_note" "biology\Unit 3_ ENERGY TRANSFORMATION\flashcard"
mkdir "biology\Unit 4_ EVOLUTION\video" "biology\Unit 4_ EVOLUTION\quiz" "biology\Unit 4_ EVOLUTION\exam" "biology\Unit 4_ EVOLUTION\past_paper" "biology\Unit 4_ EVOLUTION\short_note" "biology\Unit 4_ EVOLUTION\flashcard"
mkdir "biology\Unit 5_ HUMAN BODY SYSTEM\video" "biology\Unit 5_ HUMAN BODY SYSTEM\quiz" "biology\Unit 5_ HUMAN BODY SYSTEM\exam" "biology\Unit 5_ HUMAN BODY SYSTEM\past_paper" "biology\Unit 5_ HUMAN BODY SYSTEM\short_note" "biology\Unit 5_ HUMAN BODY SYSTEM\flashcard"
mkdir "biology\Unit 6_ CLIMATE CHANGE\video" "biology\Unit 6_ CLIMATE CHANGE\quiz" "biology\Unit 6_ CLIMATE CHANGE\exam" "biology\Unit 6_ CLIMATE CHANGE\past_paper" "biology\Unit 6_ CLIMATE CHANGE\short_note" "biology\Unit 6_ CLIMATE CHANGE\flashcard"

REM ========== IT ==========
mkdir "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\video" "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\quiz" "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\exam" "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\past_paper" "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\short_note" "it\Unit 1_ INFORMATION SYSTEMS AND THEIR APPLICATIONS\flashcard"
mkdir "it\Unit 2_ EMERGING TECHNOLOGIES\video" "it\Unit 2_ EMERGING TECHNOLOGIES\quiz" "it\Unit 2_ EMERGING TECHNOLOGIES\exam" "it\Unit 2_ EMERGING TECHNOLOGIES\past_paper" "it\Unit 2_ EMERGING TECHNOLOGIES\short_note" "it\Unit 2_ EMERGING TECHNOLOGIES\flashcard"
mkdir "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\video" "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\quiz" "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\exam" "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\past_paper" "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\short_note" "it\Unit 3_ DATABASE MANAGEMENT SYSTEM\flashcard"
mkdir "it\Unit 4_ WEB AUTHORING\video" "it\Unit 4_ WEB AUTHORING\quiz" "it\Unit 4_ WEB AUTHORING\exam" "it\Unit 4_ WEB AUTHORING\past_paper" "it\Unit 4_ WEB AUTHORING\short_note" "it\Unit 4_ WEB AUTHORING\flashcard"
mkdir "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\video" "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\quiz" "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\exam" "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\past_paper" "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\short_note" "it\Unit 5_ MAINTENANCE AND TROUBLESHOOTING\flashcard"
mkdir "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\video" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\quiz" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\exam" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\past_paper" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\short_note" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Unit 1_ SUSTAINABLE DEVELOPMENT\video" "english\Unit 1_ SUSTAINABLE DEVELOPMENT\quiz" "english\Unit 1_ SUSTAINABLE DEVELOPMENT\exam" "english\Unit 1_ SUSTAINABLE DEVELOPMENT\past_paper" "english\Unit 1_ SUSTAINABLE DEVELOPMENT\short_note" "english\Unit 1_ SUSTAINABLE DEVELOPMENT\flashcard"
mkdir "english\Unit 2_ TIME MANAGEMENT\video" "english\Unit 2_ TIME MANAGEMENT\quiz" "english\Unit 2_ TIME MANAGEMENT\exam" "english\Unit 2_ TIME MANAGEMENT\past_paper" "english\Unit 2_ TIME MANAGEMENT\short_note" "english\Unit 2_ TIME MANAGEMENT\flashcard"
mkdir "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\video" "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\quiz" "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\exam" "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\past_paper" "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\short_note" "english\Unit 3_ EVIDENCE ON TRAFFIC ACCIDENT\flashcard"
mkdir "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\video" "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\quiz" "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\exam" "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\past_paper" "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\short_note" "english\Unit 4_ NATURAL RESOURCE MANAGEMENT\flashcard"
mkdir "english\Unit 5_ MECHANIZED AGRICULTURE\video" "english\Unit 5_ MECHANIZED AGRICULTURE\quiz" "english\Unit 5_ MECHANIZED AGRICULTURE\exam" "english\Unit 5_ MECHANIZED AGRICULTURE\past_paper" "english\Unit 5_ MECHANIZED AGRICULTURE\short_note" "english\Unit 5_ MECHANIZED AGRICULTURE\flashcard"
mkdir "english\Unit 6_ GREEN ECONOMIES\video" "english\Unit 6_ GREEN ECONOMIES\quiz" "english\Unit 6_ GREEN ECONOMIES\exam" "english\Unit 6_ GREEN ECONOMIES\past_paper" "english\Unit 6_ GREEN ECONOMIES\short_note" "english\Unit 6_ GREEN ECONOMIES\flashcard"
mkdir "english\Unit 7_ NATIONAL PRIDE\video" "english\Unit 7_ NATIONAL PRIDE\quiz" "english\Unit 7_ NATIONAL PRIDE\exam" "english\Unit 7_ NATIONAL PRIDE\past_paper" "english\Unit 7_ NATIONAL PRIDE\short_note" "english\Unit 7_ NATIONAL PRIDE\flashcard"
mkdir "english\Unit 8_ TELEMEDICINE\video" "english\Unit 8_ TELEMEDICINE\quiz" "english\Unit 8_ TELEMEDICINE\exam" "english\Unit 8_ TELEMEDICINE\past_paper" "english\Unit 8_ TELEMEDICINE\short_note" "english\Unit 8_ TELEMEDICINE\flashcard"
mkdir "english\Unit 9_ CONFLICT MANAGEMENT\video" "english\Unit 9_ CONFLICT MANAGEMENT\quiz" "english\Unit 9_ CONFLICT MANAGEMENT\exam" "english\Unit 9_ CONFLICT MANAGEMENT\past_paper" "english\Unit 9_ CONFLICT MANAGEMENT\short_note" "english\Unit 9_ CONFLICT MANAGEMENT\flashcard"
mkdir "english\Unit 10_ ROBOTICS\video" "english\Unit 10_ ROBOTICS\quiz" "english\Unit 10_ ROBOTICS\exam" "english\Unit 10_ ROBOTICS\past_paper" "english\Unit 10_ ROBOTICS\short_note" "english\Unit 10_ ROBOTICS\flashcard"

REM ========== AGRICULTURE ==========
mkdir "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 1_ VEGETABLE CROPS PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 2_ FRUIT CROPS PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 3_ ROOT AND TUBER CROPS PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 4_ COFFEE, TEA AND SPICES PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\video" "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\quiz" "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\exam" "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\past_paper" "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\short_note" "agriculture\Unit 5_ INTRODUCTION TO PLANT BIOTECHNOLOGY\flashcard"
mkdir "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 6_ BEEF CATTLE PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 7_ SHEEP AND GOAT PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 8_ CAMEL PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 9_ POULTRY PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 10_ FISHERY PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 11_ APICULTURE\video" "agriculture\Unit 11_ APICULTURE\quiz" "agriculture\Unit 11_ APICULTURE\exam" "agriculture\Unit 11_ APICULTURE\past_paper" "agriculture\Unit 11_ APICULTURE\short_note" "agriculture\Unit 11_ APICULTURE\flashcard"
mkdir "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\video" "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\quiz" "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\exam" "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\past_paper" "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\short_note" "agriculture\Unit 12_ NURSERY AND PLANTATION TECHNOLOGY\flashcard"
mkdir "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\video" "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\quiz" "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\exam" "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\past_paper" "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\short_note" "agriculture\Unit 13_ BASICS OF AGRO-FORESTRY SYSTEMS AND PRACTICES\flashcard"
mkdir "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\video" "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\quiz" "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\exam" "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\past_paper" "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\short_note" "agriculture\Unit 14_ SOIL AND WATER CONSERVATION\flashcard"
mkdir "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\video" "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\quiz" "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\exam" "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\past_paper" "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\short_note" "agriculture\Unit 15_ GENDER AND HUMAN NUTRITION\flashcard"
mkdir "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\video" "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\quiz" "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\exam" "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\past_paper" "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\short_note" "agriculture\Unit 16_ SAFE FOOD PRODUCTION AND POSTHARVEST HANDLING\flashcard"
mkdir "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\video" "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\quiz" "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\exam" "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\past_paper" "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\short_note" "agriculture\Unit 17_ APPLICATION OF INFORMATION AND COMMUNICATION TECHNOLOGIES (ICT) IN AGRICULTURE\flashcard"

REM ========== APTITUDE (Special Parts) ==========
mkdir "aptitude\Part 1_ Mathematical Part\video" "aptitude\Part 1_ Mathematical Part\quiz" "aptitude\Part 1_ Mathematical Part\exam" "aptitude\Part 1_ Mathematical Part\past_paper" "aptitude\Part 1_ Mathematical Part\short_note" "aptitude\Part 1_ Mathematical Part\flashcard"
mkdir "aptitude\Part 2_ English Part\video" "aptitude\Part 2_ English Part\quiz" "aptitude\Part 2_ English Part\exam" "aptitude\Part 2_ English Part\past_paper" "aptitude\Part 2_ English Part\short_note" "aptitude\Part 2_ English Part\flashcard"

echo Grade 12 Natural Science folder structure completed!
pause