@echo off
echo Creating Grade 11 Social Science folder structure with subfolders...

mkdir "Grade_11_Social_Science"
cd "Grade_11_Social_Science"

mkdir mathematics economics history geography citizenship it english aptitude

REM ========== MATHEMATICS ==========
mkdir "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\video" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\quiz" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\exam" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\past_paper" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\short_note" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\flashcard"
mkdir "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\video" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\quiz" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\exam" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\past_paper" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\short_note" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\flashcard"
mkdir "mathematics\Unit 3_ MATRICES\video" "mathematics\Unit 3_ MATRICES\quiz" "mathematics\Unit 3_ MATRICES\exam" "mathematics\Unit 3_ MATRICES\past_paper" "mathematics\Unit 3_ MATRICES\short_note" "mathematics\Unit 3_ MATRICES\flashcard"
mkdir "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\video" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\quiz" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\exam" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\past_paper" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\short_note" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\flashcard"
mkdir "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\video" "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\quiz" "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\exam" "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\past_paper" "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\short_note" "mathematics\Unit 5_ POPULATION AND NATURAL RESOURCES\flashcard"

REM ========== ECONOMICS ==========
mkdir "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\video" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\quiz" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\exam" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\past_paper" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\short_note" "economics\Unit 1_ THEORY OF CONSUMER BEHAVIOR AND DEMAND\flashcard"
mkdir "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\video" "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\quiz" "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\exam" "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\past_paper" "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\short_note" "economics\Unit 2_ MARKET STRUCTURE AND THE DECISION OF FIRMS\flashcard"
mkdir "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\video" "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\quiz" "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\exam" "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\past_paper" "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\short_note" "economics\Unit 3_ NATIONAL INCOME ACCOUNTING\flashcard"
mkdir "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\video" "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\quiz" "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\exam" "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\past_paper" "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\short_note" "economics\Unit 4_ CONSUMPTION, SAVING AND INVESTMENT\flashcard"
mkdir "economics\Unit 5_ TRADE AND FINANCE\video" "economics\Unit 5_ TRADE AND FINANCE\quiz" "economics\Unit 5_ TRADE AND FINANCE\exam" "economics\Unit 5_ TRADE AND FINANCE\past_paper" "economics\Unit 5_ TRADE AND FINANCE\short_note" "economics\Unit 5_ TRADE AND FINANCE\flashcard"
mkdir "economics\Unit 6_ ECONOMIC DEVELOPMENT\video" "economics\Unit 6_ ECONOMIC DEVELOPMENT\quiz" "economics\Unit 6_ ECONOMIC DEVELOPMENT\exam" "economics\Unit 6_ ECONOMIC DEVELOPMENT\past_paper" "economics\Unit 6_ ECONOMIC DEVELOPMENT\short_note" "economics\Unit 6_ ECONOMIC DEVELOPMENT\flashcard"
mkdir "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\video" "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\quiz" "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\exam" "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\past_paper" "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\short_note" "economics\Unit 7_ MAIN SECTORS, SECTORIAL POLICIES AND STRATEGIES OF ETHIOPIA\flashcard"

REM ========== HISTORY ==========
mkdir "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\video" "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\quiz" "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\exam" "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\past_paper" "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\short_note" "history\Unit 1_ HISTORY, HISTORIOGRAPHY, AND HUMAN EVOLUTION\flashcard"
mkdir "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\video" "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\quiz" "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\exam" "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\past_paper" "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\short_note" "history\Unit 2_ MAJOR SPOTS OF ANCIENT WORLD CIVILIZATIONS UP TO c.500 A.D.\flashcard"
mkdir "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\video" "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\quiz" "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\exam" "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\past_paper" "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\short_note" "history\Unit 3_ PEOPLES, STATES AND HISTORICAL PROCESSES IN ETHIOPIA AND THE HORN TO THE END OF THE 13TH CENTURY\flashcard"
mkdir "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\video" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\quiz" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\exam" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\past_paper" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\short_note" "history\Unit 4_ THE MIDDLE AGES AND EARLY MODERN WORLD, C. 500 AD-1789\flashcard"
mkdir "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\video" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\quiz" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\exam" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\past_paper" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\short_note" "history\Unit 5_ PEOPLES AND STATES OF AFRICA TO 1500\flashcard"
mkdir "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\video" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\quiz" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\exam" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\past_paper" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\short_note" "history\Unit 6_ AFRICA AND THE OUTSIDE WORLD 1500-1880s\flashcard"
mkdir "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\video" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\quiz" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\exam" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\past_paper" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\short_note" "history\Unit 7_ STATES, PRINCIPALITIES, POPULATION MOVEMENTS AND INTERACTIONS IN ETHIOPIA\flashcard"
mkdir "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\video" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\quiz" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\exam" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\past_paper" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\short_note" "history\Unit 8_ POLITICAL, SOCIAL AND ECONOMIC PROCESSES IN ETHIOPIA, MID 16TH TO MID-19TH CENTURY\flashcard"
mkdir "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\video" "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\quiz" "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\exam" "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\past_paper" "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\short_note" "history\Unit 9_ THE AGE OF REVOLUTIONS, 1789 TO 1815\flashcard"

REM ========== GEOGRAPHY ==========
mkdir "geography\Unit 1_ FORMATION OF THE CONTINENTS\video" "geography\Unit 1_ FORMATION OF THE CONTINENTS\quiz" "geography\Unit 1_ FORMATION OF THE CONTINENTS\exam" "geography\Unit 1_ FORMATION OF THE CONTINENTS\past_paper" "geography\Unit 1_ FORMATION OF THE CONTINENTS\short_note" "geography\Unit 1_ FORMATION OF THE CONTINENTS\flashcard"
mkdir "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\video" "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\quiz" "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\exam" "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\past_paper" "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\short_note" "geography\Unit 2_ CLIMATE CLASSIFICATION AND CLIMATE REGIONS OF OUR WORLD\flashcard"
mkdir "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\video" "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\quiz" "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\exam" "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\past_paper" "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\short_note" "geography\Unit 3_ NATURAL RESOURCES AND CONFLICTS OVER RESOURCES\flashcard"
mkdir "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\video" "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\quiz" "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\exam" "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\past_paper" "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\short_note" "geography\Unit 4_ GLOBAL POPULATION DYNAMICS AND CHALLENGES\flashcard"
mkdir "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\video" "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\quiz" "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\exam" "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\past_paper" "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\short_note" "geography\Unit 5_ GEOGRAPHY AND ECONOMIC DEVELOPMENT\flashcard"
mkdir "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\video" "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\quiz" "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\exam" "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\past_paper" "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\short_note" "geography\Unit 6_ MAJOR GLOBAL ENVIRONMENTAL CHANGES\flashcard"
mkdir "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\video" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\quiz" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\exam" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\past_paper" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\short_note" "geography\Unit 7_ GEOGRAPHIC ISSUES AND PUBLIC CONCERNS\flashcard"
mkdir "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\video" "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\quiz" "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\exam" "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\past_paper" "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\short_note" "geography\Unit 8_ GEO-SPATIAL INFORMATION AND DATA PROCESSING\flashcard"

REM ========== CITIZENSHIP ==========
mkdir "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\video" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\quiz" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\exam" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\past_paper" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\short_note" "citizenship\Unit 1_ DEMOCRACY AND DEMOCRATIZATION\flashcard"
mkdir "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\video" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\quiz" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\exam" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\past_paper" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\short_note" "citizenship\Unit 2_ CITIZENS IN THE DIGITAL TECHNOLOGY AGE\flashcard"
mkdir "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\video" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\quiz" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\exam" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\past_paper" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\short_note" "citizenship\Unit 3_ UNDERSTANDING GOOD GOVERNANCE\flashcard"
mkdir "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\video" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\quiz" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\exam" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\past_paper" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\short_note" "citizenship\Unit 4_ PEACE AND INDIGENOUS CONFLICT RESOLUTION MECHANISMS\flashcard"
mkdir "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\video" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\quiz" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\exam" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\past_paper" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\short_note" "citizenship\Unit 5_ FEDERALISM IN ETHIOPIA\flashcard"
mkdir "citizenship\Unit 6_ HUMAN RIGHTS\video" "citizenship\Unit 6_ HUMAN RIGHTS\quiz" "citizenship\Unit 6_ HUMAN RIGHTS\exam" "citizenship\Unit 6_ HUMAN RIGHTS\past_paper" "citizenship\Unit 6_ HUMAN RIGHTS\short_note" "citizenship\Unit 6_ HUMAN RIGHTS\flashcard"
mkdir "citizenship\Unit 7_ PATRIOTISM\video" "citizenship\Unit 7_ PATRIOTISM\quiz" "citizenship\Unit 7_ PATRIOTISM\exam" "citizenship\Unit 7_ PATRIOTISM\past_paper" "citizenship\Unit 7_ PATRIOTISM\short_note" "citizenship\Unit 7_ PATRIOTISM\flashcard"
mkdir "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\video" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\quiz" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\exam" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\past_paper" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\short_note" "citizenship\Unit 8_ GLOBALIZATION AND GLOBAL ISSUES\flashcard"

REM ========== IT ==========
mkdir "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\video" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\quiz" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\exam" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\past_paper" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\short_note" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\flashcard"
mkdir "it\Unit 2_ EMERGING TECHNOLOGIES\video" "it\Unit 2_ EMERGING TECHNOLOGIES\quiz" "it\Unit 2_ EMERGING TECHNOLOGIES\exam" "it\Unit 2_ EMERGING TECHNOLOGIES\past_paper" "it\Unit 2_ EMERGING TECHNOLOGIES\short_note" "it\Unit 2_ EMERGING TECHNOLOGIES\flashcard"
mkdir "it\Unit 3_ DATABASE MANAGEMENT\video" "it\Unit 3_ DATABASE MANAGEMENT\quiz" "it\Unit 3_ DATABASE MANAGEMENT\exam" "it\Unit 3_ DATABASE MANAGEMENT\past_paper" "it\Unit 3_ DATABASE MANAGEMENT\short_note" "it\Unit 3_ DATABASE MANAGEMENT\flashcard"
mkdir "it\Unit 4_ WEB DEVELOPMENT\video" "it\Unit 4_ WEB DEVELOPMENT\quiz" "it\Unit 4_ WEB DEVELOPMENT\exam" "it\Unit 4_ WEB DEVELOPMENT\past_paper" "it\Unit 4_ WEB DEVELOPMENT\short_note" "it\Unit 4_ WEB DEVELOPMENT\flashcard"
mkdir "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\video" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\quiz" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\exam" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\past_paper" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\short_note" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\flashcard"
mkdir "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\video" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\quiz" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\exam" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\past_paper" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\short_note" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Unit 1_ ENVIRONMENTAL HAZARDS\video" "english\Unit 1_ ENVIRONMENTAL HAZARDS\quiz" "english\Unit 1_ ENVIRONMENTAL HAZARDS\exam" "english\Unit 1_ ENVIRONMENTAL HAZARDS\past_paper" "english\Unit 1_ ENVIRONMENTAL HAZARDS\short_note" "english\Unit 1_ ENVIRONMENTAL HAZARDS\flashcard"
mkdir "english\Unit 2_ CIVILIZATION\video" "english\Unit 2_ CIVILIZATION\quiz" "english\Unit 2_ CIVILIZATION\exam" "english\Unit 2_ CIVILIZATION\past_paper" "english\Unit 2_ CIVILIZATION\short_note" "english\Unit 2_ CIVILIZATION\flashcard"
mkdir "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\video" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\quiz" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\exam" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\past_paper" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\short_note" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\flashcard"
mkdir "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\video" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\quiz" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\exam" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\past_paper" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\short_note" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\flashcard"
mkdir "english\Unit 5_ IRRIGATION\video" "english\Unit 5_ IRRIGATION\quiz" "english\Unit 5_ IRRIGATION\exam" "english\Unit 5_ IRRIGATION\past_paper" "english\Unit 5_ IRRIGATION\short_note" "english\Unit 5_ IRRIGATION\flashcard"
mkdir "english\Unit 6_ GLOBAL WARMING\video" "english\Unit 6_ GLOBAL WARMING\quiz" "english\Unit 6_ GLOBAL WARMING\exam" "english\Unit 6_ GLOBAL WARMING\past_paper" "english\Unit 6_ GLOBAL WARMING\short_note" "english\Unit 6_ GLOBAL WARMING\flashcard"
mkdir "english\Unit 7_ PATRIOTISM\video" "english\Unit 7_ PATRIOTISM\quiz" "english\Unit 7_ PATRIOTISM\exam" "english\Unit 7_ PATRIOTISM\past_paper" "english\Unit 7_ PATRIOTISM\short_note" "english\Unit 7_ PATRIOTISM\flashcard"
mkdir "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\video" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\quiz" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\exam" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\past_paper" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\short_note" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\flashcard"
mkdir "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\video" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\quiz" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\exam" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\past_paper" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\short_note" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\flashcard"
mkdir "english\Unit 10_ ARTIFICIAL INTELLIGENCE\video" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\quiz" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\exam" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\past_paper" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\short_note" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\flashcard"

REM ========== APTITUDE (Special Parts) ==========
mkdir "aptitude\Part 1_ Mathematical Part\video" "aptitude\Part 1_ Mathematical Part\quiz" "aptitude\Part 1_ Mathematical Part\exam" "aptitude\Part 1_ Mathematical Part\past_paper" "aptitude\Part 1_ Mathematical Part\short_note" "aptitude\Part 1_ Mathematical Part\flashcard"
mkdir "aptitude\Part 2_ English Part\video" "aptitude\Part 2_ English Part\quiz" "aptitude\Part 2_ English Part\exam" "aptitude\Part 2_ English Part\past_paper" "aptitude\Part 2_ English Part\short_note" "aptitude\Part 2_ English Part\flashcard"

echo Grade 11 Social Science folder structure completed!
pause