@echo off
echo Creating Grade 11 Natural Science folder structure with subfolders...

mkdir "Grade_11_Natural_Science"
cd "Grade_11_Natural_Science"

mkdir mathematics physics chemistry biology it english aptitude agriculture

REM ========== MATHEMATICS ==========
mkdir "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\video" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\quiz" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\exam" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\past_paper" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\short_note" "mathematics\Unit 1_ RELATIONS AND FUNCTIONS\flashcard"
mkdir "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\video" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\quiz" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\exam" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\past_paper" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\short_note" "mathematics\Unit 2_ RATIONAL EXPRESSIONS AND RATIONAL FUNCTIONS\flashcard"
mkdir "mathematics\Unit 3_ MATRICES\video" "mathematics\Unit 3_ MATRICES\quiz" "mathematics\Unit 3_ MATRICES\exam" "mathematics\Unit 3_ MATRICES\past_paper" "mathematics\Unit 3_ MATRICES\short_note" "mathematics\Unit 3_ MATRICES\flashcard"
mkdir "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\video" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\quiz" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\exam" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\past_paper" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\short_note" "mathematics\Unit 4_ DETERMINANTS AND THEIR PROPERTIES\flashcard"
mkdir "mathematics\Unit 5_ VECTORS\video" "mathematics\Unit 5_ VECTORS\quiz" "mathematics\Unit 5_ VECTORS\exam" "mathematics\Unit 5_ VECTORS\past_paper" "mathematics\Unit 5_ VECTORS\short_note" "mathematics\Unit 5_ VECTORS\flashcard"

REM ========== PHYSICS ==========
mkdir "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\video" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\quiz" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\exam" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\past_paper" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\short_note" "physics\Unit 1_ PHYSICS AND HUMAN SOCIETY\flashcard"
mkdir "physics\Unit 2_ VECTORS\video" "physics\Unit 2_ VECTORS\quiz" "physics\Unit 2_ VECTORS\exam" "physics\Unit 2_ VECTORS\past_paper" "physics\Unit 2_ VECTORS\short_note" "physics\Unit 2_ VECTORS\flashcard"
mkdir "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\video" "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\quiz" "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\exam" "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\past_paper" "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\short_note" "physics\Unit 3_ MOTION IN ONE AND TWO DIMENSIONS\flashcard"
mkdir "physics\Unit 4_ DYNAMICS\video" "physics\Unit 4_ DYNAMICS\quiz" "physics\Unit 4_ DYNAMICS\exam" "physics\Unit 4_ DYNAMICS\past_paper" "physics\Unit 4_ DYNAMICS\short_note" "physics\Unit 4_ DYNAMICS\flashcard"
mkdir "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\video" "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\quiz" "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\exam" "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\past_paper" "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\short_note" "physics\Unit 5_ HEAT CONDUCTION AND CALORIMETRY\flashcard"
mkdir "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\video" "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\quiz" "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\exam" "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\past_paper" "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\short_note" "physics\Unit 6_ ELECTROSTATICS AND ELECTRIC CIRCUIT\flashcard"
mkdir "physics\Unit 7_ NUCLEAR PHYSICS\video" "physics\Unit 7_ NUCLEAR PHYSICS\quiz" "physics\Unit 7_ NUCLEAR PHYSICS\exam" "physics\Unit 7_ NUCLEAR PHYSICS\past_paper" "physics\Unit 7_ NUCLEAR PHYSICS\short_note" "physics\Unit 7_ NUCLEAR PHYSICS\flashcard"

REM ========== CHEMISTRY ==========
mkdir "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\video" "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\quiz" "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\exam" "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\past_paper" "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\short_note" "chemistry\Unit 1_ ATOMIC STRUCTURE AND PERIODIC PROPERTIES OF THE ELEMENTS\flashcard"
mkdir "chemistry\Unit 2_ CHEMICAL BONDING\video" "chemistry\Unit 2_ CHEMICAL BONDING\quiz" "chemistry\Unit 2_ CHEMICAL BONDING\exam" "chemistry\Unit 2_ CHEMICAL BONDING\past_paper" "chemistry\Unit 2_ CHEMICAL BONDING\short_note" "chemistry\Unit 2_ CHEMICAL BONDING\flashcard"
mkdir "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\video" "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\quiz" "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\exam" "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\past_paper" "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\short_note" "chemistry\Unit 3_ PHYSICAL STATES OF MATTER\flashcard"
mkdir "chemistry\Unit 4_ CHEMICAL KINETICS\video" "chemistry\Unit 4_ CHEMICAL KINETICS\quiz" "chemistry\Unit 4_ CHEMICAL KINETICS\exam" "chemistry\Unit 4_ CHEMICAL KINETICS\past_paper" "chemistry\Unit 4_ CHEMICAL KINETICS\short_note" "chemistry\Unit 4_ CHEMICAL KINETICS\flashcard"
mkdir "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\video" "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\quiz" "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\exam" "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\past_paper" "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\short_note" "chemistry\Unit 5_ CHEMICAL EQUILIBRIUM\flashcard"
mkdir "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\video" "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\quiz" "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\exam" "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\past_paper" "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\short_note" "chemistry\Unit 6_ SOME IMPORTANT OXYGEN-CONTAINING ORGANIC COMPOUNDS\flashcard"

REM ========== BIOLOGY ==========
mkdir "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\video" "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\quiz" "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\exam" "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\past_paper" "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\short_note" "biology\Unit 1_ BIOLOGY AND TECHNOLOGY\flashcard"
mkdir "biology\Unit 2_ ANIMALS\video" "biology\Unit 2_ ANIMALS\quiz" "biology\Unit 2_ ANIMALS\exam" "biology\Unit 2_ ANIMALS\past_paper" "biology\Unit 2_ ANIMALS\short_note" "biology\Unit 2_ ANIMALS\flashcard"
mkdir "biology\Unit 3_ ENZYMES\video" "biology\Unit 3_ ENZYMES\quiz" "biology\Unit 3_ ENZYMES\exam" "biology\Unit 3_ ENZYMES\past_paper" "biology\Unit 3_ ENZYMES\short_note" "biology\Unit 3_ ENZYMES\flashcard"
mkdir "biology\Unit 4_ GENETICS\video" "biology\Unit 4_ GENETICS\quiz" "biology\Unit 4_ GENETICS\exam" "biology\Unit 4_ GENETICS\past_paper" "biology\Unit 4_ GENETICS\short_note" "biology\Unit 4_ GENETICS\flashcard"
mkdir "biology\Unit 5_ THE HUMAN BODY SYSTEMS\video" "biology\Unit 5_ THE HUMAN BODY SYSTEMS\quiz" "biology\Unit 5_ THE HUMAN BODY SYSTEMS\exam" "biology\Unit 5_ THE HUMAN BODY SYSTEMS\past_paper" "biology\Unit 5_ THE HUMAN BODY SYSTEMS\short_note" "biology\Unit 5_ THE HUMAN BODY SYSTEMS\flashcard"
mkdir "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\video" "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\quiz" "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\exam" "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\past_paper" "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\short_note" "biology\Unit 6_ POPULATION AND NATURAL RESOURCES\flashcard"

REM ========== IT ==========
mkdir "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\video" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\quiz" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\exam" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\past_paper" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\short_note" "it\Unit 1_ INFORMATION SYSTEMS AND ITS APPLICATIONS\flashcard"
mkdir "it\Unit 2_ EMERGING TECHNOLOGIES\video" "it\Unit 2_ EMERGING TECHNOLOGIES\quiz" "it\Unit 2_ EMERGING TECHNOLOGIES\exam" "it\Unit 2_ EMERGING TECHNOLOGIES\past_paper" "it\Unit 2_ EMERGING TECHNOLOGIES\short_note" "it\Unit 2_ EMERGING TECHNOLOGIES\flashcard"
mkdir "it\Unit 3_ DATABASE MANAGEMENT\video" "it\Unit 3_ DATABASE MANAGEMENT\quiz" "it\Unit 3_ DATABASE MANAGEMENT\exam" "it\Unit 3_ DATABASE MANAGEMENT\past_paper" "it\Unit 3_ DATABASE MANAGEMENT\short_note" "it\Unit 3_ DATABASE MANAGEMENT\flashcard"
mkdir "it\Unit 4_ WEB DEVELOPMENT\video" "it\Unit 4_ WEB DEVELOPMENT\quiz" "it\Unit 4_ WEB DEVELOPMENT\exam" "it\Unit 4_ WEB DEVELOPMENT\past_paper" "it\Unit 4_ WEB DEVELOPMENT\short_note" "it\Unit 4_ WEB DEVELOPMENT\flashcard"
mkdir "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\video" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\quiz" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\exam" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\past_paper" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\short_note" "it\Unit 5_ HARDWARE TROUBLESHOOTING AND PREVENTIVE MAINTENANCE\flashcard"
mkdir "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\video" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\quiz" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\exam" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\past_paper" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\short_note" "it\Unit 6_ FUNDAMENTALS OF PROGRAMMING\flashcard"

REM ========== ENGLISH ==========
mkdir "english\Unit 1_ ENVIRONMENTAL HAZARDS\video" "english\Unit 1_ ENVIRONMENTAL HAZARDS\quiz" "english\Unit 1_ ENVIRONMENTAL HAZARDS\exam" "english\Unit 1_ ENVIRONMENTAL HAZARDS\past_paper" "english\Unit 1_ ENVIRONMENTAL HAZARDS\short_note" "english\Unit 1_ ENVIRONMENTAL HAZARDS\flashcard"
mkdir "english\Unit 2_ CIVILIZATION\video" "english\Unit 2_ CIVILIZATION\quiz" "english\Unit 2_ CIVILIZATION\exam" "english\Unit 2_ CIVILIZATION\past_paper" "english\Unit 2_ CIVILIZATION\short_note" "english\Unit 2_ CIVILIZATION\flashcard"
mkdir "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\video" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\quiz" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\exam" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\past_paper" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\short_note" "english\Unit 3_ CAUSES OF ROAD TRAFFIC ACCIDENTS\flashcard"
mkdir "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\video" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\quiz" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\exam" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\past_paper" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\short_note" "english\Unit 4_ PEOPLE AND NATURAL RESOURCES\flashcard"
mkdir "english\Unit 5_ IRRIGATION\video" "english\Unit 5_ IRRIGATION\quiz" "english\Unit 5_ IRRIGATION\exam" "english\Unit 5_ IRRIGATION\past_paper" "english\Unit 5_ IRRIGATION\short_note" "english\Unit 5_ IRRIGATION\flashcard"
mkdir "english\Unit 6_ GLOBAL WARMING\video" "english\Unit 6_ GLOBAL WARMING\quiz" "english\Unit 6_ GLOBAL WARMING\exam" "english\Unit 6_ GLOBAL WARMING\past_paper" "english\Unit 6_ GLOBAL WARMING\short_note" "english\Unit 6_ GLOBAL WARMING\flashcard"
mkdir "english\Unit 7_ PATRIOTISM\video" "english\Unit 7_ PATRIOTISM\quiz" "english\Unit 7_ PATRIOTISM\exam" "english\Unit 7_ PATRIOTISM\past_paper" "english\Unit 7_ PATRIOTISM\short_note" "english\Unit 7_ PATRIOTISM\flashcard"
mkdir "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\video" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\quiz" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\exam" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\past_paper" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\short_note" "english\Unit 8_ EFFICIENCY OF HEALTH SERVICES\flashcard"
mkdir "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\video" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\quiz" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\exam" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\past_paper" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\short_note" "english\Unit 9_ INDIGENOUS CONFLICT RESOLUTION\flashcard"
mkdir "english\Unit 10_ ARTIFICIAL INTELLIGENCE\video" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\quiz" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\exam" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\past_paper" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\short_note" "english\Unit 10_ ARTIFICIAL INTELLIGENCE\flashcard"

REM ========== AGRICULTURE ==========
mkdir "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\video" "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\quiz" "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\exam" "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\past_paper" "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\short_note" "agriculture\Unit 1_ INTRODUCTION TO CROP PRODUCTION\flashcard"
mkdir "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 2_ FIELD CROPS PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 3_ INDUSTRIAL CROPS PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\video" "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\quiz" "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\exam" "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\past_paper" "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\short_note" "agriculture\Unit 4_ INTRODUCTION TO FARM ANIMALS\flashcard"
mkdir "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\video" "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\quiz" "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\exam" "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\past_paper" "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\short_note" "agriculture\Unit 5_ ANIMAL FEEDS AND FEEDING PRACTICES\flashcard"
mkdir "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\video" "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\quiz" "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\exam" "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\past_paper" "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\short_note" "agriculture\Unit 6_ ANIMAL GENETICS AND BREEDING PRACTICES\flashcard"
mkdir "agriculture\Unit 7_ FARM ANIMALS HOUSING\video" "agriculture\Unit 7_ FARM ANIMALS HOUSING\quiz" "agriculture\Unit 7_ FARM ANIMALS HOUSING\exam" "agriculture\Unit 7_ FARM ANIMALS HOUSING\past_paper" "agriculture\Unit 7_ FARM ANIMALS HOUSING\short_note" "agriculture\Unit 7_ FARM ANIMALS HOUSING\flashcard"
mkdir "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\video" "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\quiz" "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\exam" "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\past_paper" "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\short_note" "agriculture\Unit 8_ BASIC ANIMAL HEALTH AND DISEASE CONTROL\flashcard"
mkdir "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\video" "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\quiz" "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\exam" "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\past_paper" "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\short_note" "agriculture\Unit 9_ DAIRY CATTLE PRODUCTION AND MANAGEMENT\flashcard"
mkdir "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\video" "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\quiz" "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\exam" "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\past_paper" "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\short_note" "agriculture\Unit 10_ INTRODUCTION TO NATURAL RESOURCES\flashcard"
mkdir "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\video" "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\quiz" "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\exam" "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\past_paper" "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\short_note" "agriculture\Unit 11_ MANAGEMENT OF NATURAL RESOURCES\flashcard"
mkdir "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\video" "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\quiz" "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\exam" "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\past_paper" "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\short_note" "agriculture\Unit 12_ CONCEPTS OF BIODIVERSITY\flashcard"
mkdir "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\video" "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\quiz" "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\exam" "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\past_paper" "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\short_note" "agriculture\Unit 13_ CLIMATE CHANGE ADAPTATION AND MITIGATION\flashcard"
mkdir "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\video" "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\quiz" "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\exam" "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\past_paper" "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\short_note" "agriculture\Unit 14_ INTRODUCTION TO HUMAN NUTRITION\flashcard"
mkdir "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\video" "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\quiz" "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\exam" "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\past_paper" "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\short_note" "agriculture\Unit 15_ DIVERSIFIED FOOD PRODUCTION AND CONSUMPTION\flashcard"

REM ========== APTITUDE (Special Parts) ==========
mkdir "aptitude\Part 1_ Mathematical Part\video" "aptitude\Part 1_ Mathematical Part\quiz" "aptitude\Part 1_ Mathematical Part\exam" "aptitude\Part 1_ Mathematical Part\past_paper" "aptitude\Part 1_ Mathematical Part\short_note" "aptitude\Part 1_ Mathematical Part\flashcard"
mkdir "aptitude\Part 2_ English Part\video" "aptitude\Part 2_ English Part\quiz" "aptitude\Part 2_ English Part\exam" "aptitude\Part 2_ English Part\past_paper" "aptitude\Part 2_ English Part\short_note" "aptitude\Part 2_ English Part\flashcard"

echo Grade 11 Natural Science folder structure completed!
pause