@echo off
echo Creating Pre-Engineering Courses folder structure with subfolders...

mkdir "Pre_Engineering_Courses"
cd "Pre_Engineering_Courses"

mkdir "C++ Programming" "Moral and Citizenship Education" "Applied Mathematics" "Entrepreneurship" "Emerging Technologies" "English Skill 2" "Anthropology" "History"

REM ========== C++ PROGRAMMING ==========
mkdir "C++ Programming\Chapter 1_ Introduction to C++ Programming\video" "C++ Programming\Chapter 1_ Introduction to C++ Programming\quiz" "C++ Programming\Chapter 1_ Introduction to C++ Programming\exam" "C++ Programming\Chapter 1_ Introduction to C++ Programming\past_paper" "C++ Programming\Chapter 1_ Introduction to C++ Programming\short_note" "C++ Programming\Chapter 1_ Introduction to C++ Programming\flashcard"
mkdir "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\video" "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\quiz" "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\exam" "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\past_paper" "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\short_note" "C++ Programming\Chapter 2_ Basics of C++ (Comments, Case Sensitivity, Statements)\flashcard"
mkdir "C++ Programming\Chapter 3_ Primitive Data Types\video" "C++ Programming\Chapter 3_ Primitive Data Types\quiz" "C++ Programming\Chapter 3_ Primitive Data Types\exam" "C++ Programming\Chapter 3_ Primitive Data Types\past_paper" "C++ Programming\Chapter 3_ Primitive Data Types\short_note" "C++ Programming\Chapter 3_ Primitive Data Types\flashcard"
mkdir "C++ Programming\Chapter 4_ flow of controls\video" "C++ Programming\Chapter 4_ flow of controls\quiz" "C++ Programming\Chapter 4_ flow of controls\exam" "C++ Programming\Chapter 4_ flow of controls\past_paper" "C++ Programming\Chapter 4_ flow of controls\short_note" "C++ Programming\Chapter 4_ flow of controls\flashcard"
mkdir "C++ Programming\Chapter 5_ arrays and strings\video" "C++ Programming\Chapter 5_ arrays and strings\quiz" "C++ Programming\Chapter 5_ arrays and strings\exam" "C++ Programming\Chapter 5_ arrays and strings\past_paper" "C++ Programming\Chapter 5_ arrays and strings\short_note" "C++ Programming\Chapter 5_ arrays and strings\flashcard"
mkdir "C++ Programming\Chapter 6_ functions\video" "C++ Programming\Chapter 6_ functions\quiz" "C++ Programming\Chapter 6_ functions\exam" "C++ Programming\Chapter 6_ functions\past_paper" "C++ Programming\Chapter 6_ functions\short_note" "C++ Programming\Chapter 6_ functions\flashcard"
mkdir "C++ Programming\Chapter 7_ structures and unions\video" "C++ Programming\Chapter 7_ structures and unions\quiz" "C++ Programming\Chapter 7_ structures and unions\exam" "C++ Programming\Chapter 7_ structures and unions\past_paper" "C++ Programming\Chapter 7_ structures and unions\short_note" "C++ Programming\Chapter 7_ structures and unions\flashcard"
mkdir "C++ Programming\Chapter 8_ pointers\video" "C++ Programming\Chapter 8_ pointers\quiz" "C++ Programming\Chapter 8_ pointers\exam" "C++ Programming\Chapter 8_ pointers\past_paper" "C++ Programming\Chapter 8_ pointers\short_note" "C++ Programming\Chapter 8_ pointers\flashcard"

REM ========== MORAL AND CITIZENSHIP EDUCATION ==========
mkdir "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\video" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\quiz" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\exam" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\past_paper" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\short_note" "Moral and Citizenship Education\Chapter 1_ Understanding Civics and Ethics\flashcard"
mkdir "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\video" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\quiz" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\exam" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\past_paper" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\short_note" "Moral and Citizenship Education\Chapter 2_ Approaches to Ethics\flashcard"
mkdir "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\video" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\quiz" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\exam" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\past_paper" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\short_note" "Moral and Citizenship Education\Chapter 3_ Ethical Decision Making and Moral Judgments\flashcard"
mkdir "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\video" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\quiz" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\exam" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\past_paper" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\short_note" "Moral and Citizenship Education\Chapter 4_ State, Government and Citizenship\flashcard"
mkdir "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\video" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\quiz" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\exam" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\past_paper" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\short_note" "Moral and Citizenship Education\Chapter 5_ Constitution, Democracy and Human Rights\flashcard"

REM ========== APPLIED MATHEMATICS ==========
mkdir "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\video" "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\quiz" "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\exam" "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\past_paper" "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\short_note" "Applied Mathematics\Chapter 1_ Vectors and Vector Spaces\flashcard"
mkdir "Applied Mathematics\Chapter 2_ Matrices and Determinants\video" "Applied Mathematics\Chapter 2_ Matrices and Determinants\quiz" "Applied Mathematics\Chapter 2_ Matrices and Determinants\exam" "Applied Mathematics\Chapter 2_ Matrices and Determinants\past_paper" "Applied Mathematics\Chapter 2_ Matrices and Determinants\short_note" "Applied Mathematics\Chapter 2_ Matrices and Determinants\flashcard"
mkdir "Applied Mathematics\Chapter 3_ Limit and Continuity\video" "Applied Mathematics\Chapter 3_ Limit and Continuity\quiz" "Applied Mathematics\Chapter 3_ Limit and Continuity\exam" "Applied Mathematics\Chapter 3_ Limit and Continuity\past_paper" "Applied Mathematics\Chapter 3_ Limit and Continuity\short_note" "Applied Mathematics\Chapter 3_ Limit and Continuity\flashcard"
mkdir "Applied Mathematics\Chapter 4_ Derivatives\video" "Applied Mathematics\Chapter 4_ Derivatives\quiz" "Applied Mathematics\Chapter 4_ Derivatives\exam" "Applied Mathematics\Chapter 4_ Derivatives\past_paper" "Applied Mathematics\Chapter 4_ Derivatives\short_note" "Applied Mathematics\Chapter 4_ Derivatives\flashcard"
mkdir "Applied Mathematics\Chapter 5_ Application of Derivative\video" "Applied Mathematics\Chapter 5_ Application of Derivative\quiz" "Applied Mathematics\Chapter 5_ Application of Derivative\exam" "Applied Mathematics\Chapter 5_ Application of Derivative\past_paper" "Applied Mathematics\Chapter 5_ Application of Derivative\short_note" "Applied Mathematics\Chapter 5_ Application of Derivative\flashcard"
mkdir "Applied Mathematics\Chapter 6_ Integration\video" "Applied Mathematics\Chapter 6_ Integration\quiz" "Applied Mathematics\Chapter 6_ Integration\exam" "Applied Mathematics\Chapter 6_ Integration\past_paper" "Applied Mathematics\Chapter 6_ Integration\short_note" "Applied Mathematics\Chapter 6_ Integration\flashcard"
mkdir "Applied Mathematics\Chapter 7_ Integration Techniques\video" "Applied Mathematics\Chapter 7_ Integration Techniques\quiz" "Applied Mathematics\Chapter 7_ Integration Techniques\exam" "Applied Mathematics\Chapter 7_ Integration Techniques\past_paper" "Applied Mathematics\Chapter 7_ Integration Techniques\short_note" "Applied Mathematics\Chapter 7_ Integration Techniques\flashcard"
mkdir "Applied Mathematics\Chapter 8_ Improper Integrals\video" "Applied Mathematics\Chapter 8_ Improper Integrals\quiz" "Applied Mathematics\Chapter 8_ Improper Integrals\exam" "Applied Mathematics\Chapter 8_ Improper Integrals\past_paper" "Applied Mathematics\Chapter 8_ Improper Integrals\short_note" "Applied Mathematics\Chapter 8_ Improper Integrals\flashcard"
mkdir "Applied Mathematics\Chapter 9_ Application of Integration (Area)\video" "Applied Mathematics\Chapter 9_ Application of Integration (Area)\quiz" "Applied Mathematics\Chapter 9_ Application of Integration (Area)\exam" "Applied Mathematics\Chapter 9_ Application of Integration (Area)\past_paper" "Applied Mathematics\Chapter 9_ Application of Integration (Area)\short_note" "Applied Mathematics\Chapter 9_ Application of Integration (Area)\flashcard"
mkdir "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\video" "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\quiz" "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\exam" "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\past_paper" "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\short_note" "Applied Mathematics\Chapter 10_ Volume of Solids of Revolution\flashcard"
mkdir "Applied Mathematics\Chapter 11_ Arc Length\video" "Applied Mathematics\Chapter 11_ Arc Length\quiz" "Applied Mathematics\Chapter 11_ Arc Length\exam" "Applied Mathematics\Chapter 11_ Arc Length\past_paper" "Applied Mathematics\Chapter 11_ Arc Length\short_note" "Applied Mathematics\Chapter 11_ Arc Length\flashcard"
mkdir "Applied Mathematics\Chapter 12_ Surface Area\video" "Applied Mathematics\Chapter 12_ Surface Area\quiz" "Applied Mathematics\Chapter 12_ Surface Area\exam" "Applied Mathematics\Chapter 12_ Surface Area\past_paper" "Applied Mathematics\Chapter 12_ Surface Area\short_note" "Applied Mathematics\Chapter 12_ Surface Area\flashcard"

REM ========== ENTREPRENEURSHIP ==========
mkdir "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\video" "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\quiz" "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\exam" "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\past_paper" "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\short_note" "Entrepreneurship\Chapter 1_ The Nature of Entrepreneurship\flashcard"
mkdir "Entrepreneurship\Chapter 2_ Business Planning\video" "Entrepreneurship\Chapter 2_ Business Planning\quiz" "Entrepreneurship\Chapter 2_ Business Planning\exam" "Entrepreneurship\Chapter 2_ Business Planning\past_paper" "Entrepreneurship\Chapter 2_ Business Planning\short_note" "Entrepreneurship\Chapter 2_ Business Planning\flashcard"
mkdir "Entrepreneurship\Chapter 3_ Business Formation\video" "Entrepreneurship\Chapter 3_ Business Formation\quiz" "Entrepreneurship\Chapter 3_ Business Formation\exam" "Entrepreneurship\Chapter 3_ Business Formation\past_paper" "Entrepreneurship\Chapter 3_ Business Formation\short_note" "Entrepreneurship\Chapter 3_ Business Formation\flashcard"
mkdir "Entrepreneurship\Chapter 4_ Product-Service Development\video" "Entrepreneurship\Chapter 4_ Product-Service Development\quiz" "Entrepreneurship\Chapter 4_ Product-Service Development\exam" "Entrepreneurship\Chapter 4_ Product-Service Development\past_paper" "Entrepreneurship\Chapter 4_ Product-Service Development\short_note" "Entrepreneurship\Chapter 4_ Product-Service Development\flashcard"
mkdir "Entrepreneurship\Chapter 5_ Marketing\video" "Entrepreneurship\Chapter 5_ Marketing\quiz" "Entrepreneurship\Chapter 5_ Marketing\exam" "Entrepreneurship\Chapter 5_ Marketing\past_paper" "Entrepreneurship\Chapter 5_ Marketing\short_note" "Entrepreneurship\Chapter 5_ Marketing\flashcard"
mkdir "Entrepreneurship\Chapter 6_ Business Financing\video" "Entrepreneurship\Chapter 6_ Business Financing\quiz" "Entrepreneurship\Chapter 6_ Business Financing\exam" "Entrepreneurship\Chapter 6_ Business Financing\past_paper" "Entrepreneurship\Chapter 6_ Business Financing\short_note" "Entrepreneurship\Chapter 6_ Business Financing\flashcard"
mkdir "Entrepreneurship\Chapter 7_ Managing Growth and Transition\video" "Entrepreneurship\Chapter 7_ Managing Growth and Transition\quiz" "Entrepreneurship\Chapter 7_ Managing Growth and Transition\exam" "Entrepreneurship\Chapter 7_ Managing Growth and Transition\past_paper" "Entrepreneurship\Chapter 7_ Managing Growth and Transition\short_note" "Entrepreneurship\Chapter 7_ Managing Growth and Transition\flashcard"

REM ========== EMERGING TECHNOLOGIES ==========
mkdir "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\video" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\quiz" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\exam" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\past_paper" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\short_note" "Emerging Technologies\Chapter 1_ Introduction to Emerging Technologies\flashcard"
mkdir "Emerging Technologies\Chapter 2_ Overview for Data Science\video" "Emerging Technologies\Chapter 2_ Overview for Data Science\quiz" "Emerging Technologies\Chapter 2_ Overview for Data Science\exam" "Emerging Technologies\Chapter 2_ Overview for Data Science\past_paper" "Emerging Technologies\Chapter 2_ Overview for Data Science\short_note" "Emerging Technologies\Chapter 2_ Overview for Data Science\flashcard"
mkdir "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\video" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\quiz" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\exam" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\past_paper" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\short_note" "Emerging Technologies\Chapter 3_ Introduction to Artificial Intelligence (AI)\flashcard"
mkdir "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\video" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\quiz" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\exam" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\past_paper" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\short_note" "Emerging Technologies\Chapter 4_ Internet of Things (IoT)\flashcard"
mkdir "Emerging Technologies\Chapter 5_ Augmented Reality\video" "Emerging Technologies\Chapter 5_ Augmented Reality\quiz" "Emerging Technologies\Chapter 5_ Augmented Reality\exam" "Emerging Technologies\Chapter 5_ Augmented Reality\past_paper" "Emerging Technologies\Chapter 5_ Augmented Reality\short_note" "Emerging Technologies\Chapter 5_ Augmented Reality\flashcard"
mkdir "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\video" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\quiz" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\exam" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\past_paper" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\short_note" "Emerging Technologies\Chapter 6_ Ethics and Professionalism of Emerging Technologies\flashcard"
mkdir "Emerging Technologies\Chapter 7_ Other Emerging Technologies\video" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\quiz" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\exam" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\past_paper" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\short_note" "Emerging Technologies\Chapter 7_ Other Emerging Technologies\flashcard"

REM ========== ENGLISH SKILL 2 ==========
mkdir "English Skill 2\Unit I_ Life Skills\video" "English Skill 2\Unit I_ Life Skills\quiz" "English Skill 2\Unit I_ Life Skills\exam" "English Skill 2\Unit I_ Life Skills\past_paper" "English Skill 2\Unit I_ Life Skills\short_note" "English Skill 2\Unit I_ Life Skills\flashcard"
mkdir "English Skill 2\Unit II_ Speculations about the future of Science\video" "English Skill 2\Unit II_ Speculations about the future of Science\quiz" "English Skill 2\Unit II_ Speculations about the future of Science\exam" "English Skill 2\Unit II_ Speculations about the future of Science\past_paper" "English Skill 2\Unit II_ Speculations about the future of Science\short_note" "English Skill 2\Unit II_ Speculations about the future of Science\flashcard"
mkdir "English Skill 2\Unit III_ Environmental Protection\video" "English Skill 2\Unit III_ Environmental Protection\quiz" "English Skill 2\Unit III_ Environmental Protection\exam" "English Skill 2\Unit III_ Environmental Protection\past_paper" "English Skill 2\Unit III_ Environmental Protection\short_note" "English Skill 2\Unit III_ Environmental Protection\flashcard"
mkdir "English Skill 2\Unit IV_ Indigenous Knowledge\video" "English Skill 2\Unit IV_ Indigenous Knowledge\quiz" "English Skill 2\Unit IV_ Indigenous Knowledge\exam" "English Skill 2\Unit IV_ Indigenous Knowledge\past_paper" "English Skill 2\Unit IV_ Indigenous Knowledge\short_note" "English Skill 2\Unit IV_ Indigenous Knowledge\flashcard"
mkdir "English Skill 2\Unit V_ Cultural Heritage\video" "English Skill 2\Unit V_ Cultural Heritage\quiz" "English Skill 2\Unit V_ Cultural Heritage\exam" "English Skill 2\Unit V_ Cultural Heritage\past_paper" "English Skill 2\Unit V_ Cultural Heritage\short_note" "English Skill 2\Unit V_ Cultural Heritage\flashcard"

REM ========== ANTHROPOLOGY ==========
mkdir "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\video" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\quiz" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\exam" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\past_paper" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\short_note" "Anthropology\Unit 1_ Introducing Anthropology and its Subject Matter\flashcard"
mkdir "Anthropology\Unit 2_ Human Culture and Ties that Connect\video" "Anthropology\Unit 2_ Human Culture and Ties that Connect\quiz" "Anthropology\Unit 2_ Human Culture and Ties that Connect\exam" "Anthropology\Unit 2_ Human Culture and Ties that Connect\past_paper" "Anthropology\Unit 2_ Human Culture and Ties that Connect\short_note" "Anthropology\Unit 2_ Human Culture and Ties that Connect\flashcard"
mkdir "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\video" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\quiz" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\exam" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\past_paper" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\short_note" "Anthropology\Unit 3_ Human Diversity, Culture Areas and Contact in Ethiopia\flashcard"
mkdir "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\video" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\quiz" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\exam" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\past_paper" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\short_note" "Anthropology\Unit 4_ Marginalized, Minorities, and Vulnerable Groups\flashcard"
mkdir "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\video" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\quiz" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\exam" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\past_paper" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\short_note" "Anthropology\Unit 5_ Identity, Inter-Ethnic Relations and Multiculturalism in Ethiopia\flashcard"
mkdir "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\video" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\quiz" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\exam" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\past_paper" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\short_note" "Anthropology\Unit 6_ Customary and Local Governance Systems and Peace Making\flashcard"
mkdir "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\video" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\quiz" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\exam" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\past_paper" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\short_note" "Anthropology\Unit 7_ Indigenous Knowledge Systems (IKS) and Practices\flashcard"

REM ========== HISTORY ==========
mkdir "History\Chapter 1_ introduction\video" "History\Chapter 1_ introduction\quiz" "History\Chapter 1_ introduction\exam" "History\Chapter 1_ introduction\past_paper" "History\Chapter 1_ introduction\short_note" "History\Chapter 1_ introduction\flashcard"
mkdir "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\video" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\quiz" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\exam" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\past_paper" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\short_note" "History\Chapter 2_ peoples and cultures in Ethiopia and the horn\flashcard"
mkdir "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\video" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\quiz" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\exam" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\past_paper" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\short_note" "History\Chapter 3_ politics, economy and socio cultural processes in Ethiopia to end of the 13th century\flashcard"
mkdir "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\video" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\quiz" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\exam" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\past_paper" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\short_note" "History\Chapter 4_ politics, economy and socio cultural processes in Ethiopia from late 13th to 16th century\flashcard"
mkdir "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\video" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\quiz" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\exam" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\past_paper" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\short_note" "History\Chapter 5_ politics, economy and socio cultural processes in Ethiopia from early 16th to 18th century\flashcard"
mkdir "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\video" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\quiz" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\exam" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\past_paper" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\short_note" "History\Chapter 6_ internal interactions and external relations in Ethiopia 1800-1941\flashcard"
mkdir "History\Chapter 7_ internal developments and external relations, 1941-1994\video" "History\Chapter 7_ internal developments and external relations, 1941-1994\quiz" "History\Chapter 7_ internal developments and external relations, 1941-1994\exam" "History\Chapter 7_ internal developments and external relations, 1941-1994\past_paper" "History\Chapter 7_ internal developments and external relations, 1941-1994\short_note" "History\Chapter 7_ internal developments and external relations, 1941-1994\flashcard"

echo Pre-Engineering Courses folder structure completed!
pause